/*
 * GENERATED FILE - do not edit by hand. Rebuild with: node scripts/generate-timezone-cities.mjs
 *
 * Source: https://raw.githubusercontent.com/vvo/tzdb/main/raw-time-zones.json
 * Fetched: 2026-09-10 17:19 (upstream commit dcfb802986f31f6c8ddbd934f4fa9e7a3ded6bb6, 2026-09-03T17:32:43Z)
 * Licence: MIT (c) CodeAgain SASU, https://github.com/vvo/tzdb/blob/main/LICENSE
 * Regenerate with: node scripts/generate-timezone-cities.mjs
 *
 * WHAT THIS IS. One IANA zone id (the source record's own `name` field, never the source's
 * `group` field, which the generator script's header explains) mapped to @vvo/tzdb's `mainCities`
 * for that zone, in the source's own order (most populous first). 315 zones.
 *
 * WHAT THIS IS NOT. Not every one of the platform's ~418 zone ids has an entry: a zone with no
 * entry here has no vendored city (round 3, Task 4). Nothing here is inferred, translated or
 * corrected from this generator's own knowledge of geography; every row is copied from the source
 * verbatim, so a city missing from a real zone is a gap in the upstream data, not this file.
 */

import type { TimeZone } from './types';

export const TIMEZONE_CITIES: Readonly<Record<TimeZone, readonly string[]>> = {
  "Africa/Abidjan": ["Abidjan","Abobo","Bouaké","Korhogo"],
  "Africa/Accra": ["Kumasi","Accra","Tamale","Takoradi"],
  "Africa/Addis_Ababa": ["Addis Ababa","Jijiga","Gonder","Mek'ele"],
  "Africa/Algiers": ["Algiers","Oran","Constantine","Annaba"],
  "Africa/Asmara": ["Asmara","Keren","Himora","Af’abet"],
  "Africa/Bamako": ["Bamako","Sikasso","Koutiala","Ségou"],
  "Africa/Bangui": ["Bangui","Bimbo","Bégoua","Carnot"],
  "Africa/Banjul": ["Serekunda","Brikama","Bununka Kunda","Sukuta"],
  "Africa/Bissau": ["Bissau","Bairro Militar","Gabú","Contumo"],
  "Africa/Blantyre": ["Lilongwe","Blantyre","Mzuzu","Zomba"],
  "Africa/Brazzaville": ["Brazzaville","Pointe-Noire","Dolisie","Nkayi"],
  "Africa/Bujumbura": ["Bujumbura","Gitega","Ngozi","Mpanda"],
  "Africa/Cairo": ["Cairo","Alexandria","Giza","Shubrā al Khaymah"],
  "Africa/Casablanca": ["Casablanca","Rabat","Fes","Tangier"],
  "Africa/Conakry": ["Conakry","Camayenne","Nzérékoré","Kankan"],
  "Africa/Dakar": ["Dakar","Pikine","Touba","Guédiawaye"],
  "Africa/Dar_es_Salaam": ["Dar es Salaam","Mwanza","Dodoma","Zanzibar"],
  "Africa/Djibouti": ["Djibouti","Balbala","Ali Sabih","Dikhil"],
  "Africa/Douala": ["Douala","Yaoundé","Bamenda","Bafoussam"],
  "Africa/El_Aaiun": ["Laayoune","Dakhla","Boujdour","El Marsa"],
  "Africa/Freetown": ["Freetown","Kenema","Bo","Koidu"],
  "Africa/Gaborone": ["Gaborone","Francistown","Mogoditshane","Maun"],
  "Africa/Harare": ["Harare","Bulawayo","Chitungwiza","Mutare"],
  "Africa/Johannesburg": ["Johannesburg","Cape Town","Durban","Pretoria"],
  "Africa/Juba": ["Juba","Winejok","Yei","Malakal"],
  "Africa/Kampala": ["Kampala","Nansana","Kira","Bunamwaya"],
  "Africa/Khartoum": ["Khartoum","Omdurman","Khartoum North","Nyala"],
  "Africa/Kigali": ["Kigali","Gisenyi","Musanze","Nyagatare"],
  "Africa/Kinshasa": ["Kinshasa","Kikwit","Masina","Mbandaka"],
  "Africa/Lagos": ["Lagos","Kano","Ibadan","Abuja"],
  "Africa/Libreville": ["Libreville","Port-Gentil","Franceville","Owendo"],
  "Africa/Lome": ["Lomé","Sokodé","Kara","Atakpamé"],
  "Africa/Luanda": ["Luanda","Mulenvos","Viana","Kikolo"],
  "Africa/Lubumbashi": ["Lubumbashi","Mbuji-Mayi","Kananga","Kisangani"],
  "Africa/Lusaka": ["Lusaka","Kitwe","Ndola","Chipata"],
  "Africa/Malabo": ["Bata","Malabo","Ebebiyin","Ciudad de la Paz"],
  "Africa/Maputo": ["Maputo","Matola","Nampula","Beira"],
  "Africa/Maseru": ["Maseru","Maputsoe","Mohale's Hoek","Mafeteng"],
  "Africa/Mbabane": ["Manzini","Mbabane","Lobamba"],
  "Africa/Mogadishu": ["Mogadishu","Borama","Hargeysa","Berbera"],
  "Africa/Monrovia": ["Monrovia","Gbarnga","Buchanan","Ganta"],
  "Africa/Nairobi": ["Nairobi","Kakamega","Mombasa","Nakuru"],
  "Africa/Ndjamena": ["N'Djamena","Moundou","Abéché","Sarh"],
  "Africa/Niamey": ["Niamey","Maradi","Zinder","Tahoua"],
  "Africa/Nouakchott": ["Nouakchott","Nouadhibou","Kiffa","Dar Naim"],
  "Africa/Ouagadougou": ["Ouagadougou","Bobo-Dioulasso","Koudougou","Saaba"],
  "Africa/Porto-Novo": ["Cotonou","Abomey-Calavi","Porto-Novo","Parakou"],
  "Africa/Sao_Tome": ["São Tomé"],
  "Africa/Tripoli": ["Tripoli","Benghazi","Misratah","Zliten"],
  "Africa/Tunis": ["Tunis","Sfax","Sousse","Sukrah"],
  "Africa/Windhoek": ["Windhoek","Rundu","Walvis Bay","Swakopmund"],
  "America/Adak": ["Adak"],
  "America/Anchorage": ["Anchorage","Fairbanks","Juneau","Eagle River"],
  "America/Anguilla": ["The Valley"],
  "America/Antigua": ["Saint John’s"],
  "America/Argentina/Buenos_Aires": ["Buenos Aires","Córdoba","Rosario","Mar del Plata"],
  "America/Aruba": ["Oranjestad","Noord","Tanki Leendert","Santa Cruz"],
  "America/Asuncion": ["Asunción","Ciudad del Este","San Lorenzo","Capiatá"],
  "America/Atikokan": ["Atikokan"],
  "America/Barbados": ["Bridgetown"],
  "America/Belize": ["Belize City","San Ignacio","San Pedro","Orange Walk"],
  "America/Blanc-Sablon": ["Blanc-Sablon"],
  "America/Bogota": ["Bogotá","Cali","Medellín","Barranquilla"],
  "America/Cancun": ["Cancún","Chetumal","Playa del Carmen","Cozumel"],
  "America/Caracas": ["Caracas","Maracaibo","Valencia","Barquisimeto"],
  "America/Cayenne": ["Cayenne","Matoury","Saint-Laurent-du-Maroni","Kourou"],
  "America/Cayman": ["George Town","West Bay"],
  "America/Chicago": ["Chicago","Houston","San Antonio","Dallas"],
  "America/Ciudad_Juarez": ["Ciudad Juárez"],
  "America/Costa_Rica": ["San José","Limón","San Francisco","Alajuela"],
  "America/Curacao": ["Willemstad","Bandariba"],
  "America/Danmarkshavn": ["Danmarkshavn"],
  "America/Denver": ["Denver","El Paso","Albuquerque","Colorado Springs"],
  "America/Dominica": ["Roseau"],
  "America/Edmonton": ["Calgary","Edmonton","Lethbridge","Red Deer"],
  "America/El_Salvador": ["San Salvador","Soyapango","San Miguel","Santa Ana"],
  "America/Grand_Turk": ["Providenciales","Cockburn Town"],
  "America/Grenada": ["Saint George's"],
  "America/Guadeloupe": ["Les Abymes","Baie-Mahault","Le Gosier","Petit-Bourg"],
  "America/Guatemala": ["Guatemala City","Villa Nueva","Mixco","Cobán"],
  "America/Guayaquil": ["Quito","Guayaquil","Cuenca","Santo Domingo de los Colorados"],
  "America/Guyana": ["Georgetown","Linden","New Amsterdam"],
  "America/Halifax": ["Halifax","Sydney","Dartmouth","Moncton"],
  "America/Havana": ["Havana","Santiago de Cuba","Camagüey","Holguín"],
  "America/Hermosillo": ["Hermosillo","Culiacán","Mazatlán","Tepic"],
  "America/Jamaica": ["Kingston","New Kingston","Spanish Town","Portmore"],
  "America/Kralendijk": ["Kralendijk"],
  "America/La_Paz": ["La Paz","Santa Cruz de la Sierra","Cochabamba","Sucre"],
  "America/Lima": ["Lima","Callao","Arequipa","Trujillo"],
  "America/Los_Angeles": ["Los Angeles","San Diego","San Jose","San Francisco"],
  "America/Lower_Princes": ["Philipsburg"],
  "America/Managua": ["Managua","León","Masaya","Chinandega"],
  "America/Manaus": ["Manaus","Campo Grande","Cuiabá","Porto Velho"],
  "America/Marigot": ["Marigot"],
  "America/Martinique": ["Fort-de-France","Le Lamentin","Le Robert","Sainte-Marie"],
  "America/Matamoros": ["Reynosa","Heroica Matamoros","Nuevo Laredo","Ciudad Acuña"],
  "America/Mexico_City": ["Mexico City","Iztapalapa","Puebla","Ecatepec de Morelos"],
  "America/Miquelon": ["Saint-Pierre"],
  "America/Montevideo": ["Montevideo","Salto","Maldonado","Rivera"],
  "America/Montserrat": ["Brades","Plymouth"],
  "America/Nassau": ["Nassau","Lucaya","Freeport","Killarney"],
  "America/New_York": ["New York City","Brooklyn","Queens","Philadelphia"],
  "America/Noronha": ["Noronha"],
  "America/Nuuk": ["Nuuk","Scoresbysund"],
  "America/Panama": ["Panama City","San Miguelito","Juan Díaz","David"],
  "America/Paramaribo": ["Paramaribo","Blauwgrond","Latour","Pontbuiten"],
  "America/Phoenix": ["Phoenix","Tucson","Mesa","Chandler"],
  "America/Port-au-Prince": ["Port-au-Prince","Carrefour","Delmas","Pétionville"],
  "America/Port_of_Spain": ["Chaguanas","Mon Repos","San Fernando","Port of Spain"],
  "America/Puerto_Rico": ["San Juan","Bayamón","Carolina","Ponce"],
  "America/Punta_Arenas": ["Punta Arenas","Coyhaique","Puerto Natales","Puerto Aysén"],
  "America/Regina": ["Saskatoon","Regina","Nutana Sector","Confederation"],
  "America/Rio_Branco": ["Rio Branco","Cruzeiro do Sul","Sena Madureira","Benjamin Constant"],
  "America/Santiago": ["Santiago","Puente Alto","Maipú","Antofagasta"],
  "America/Santo_Domingo": ["Santo Domingo","Santiago de los Caballeros","Santo Domingo Oeste","Santo Domingo Este"],
  "America/Sao_Paulo": ["São Paulo","Rio de Janeiro","Belo Horizonte","Salvador"],
  "America/St_Barthelemy": ["Gustavia"],
  "America/St_Johns": ["St. John's","Conception Bay South","Paradise","Mount Pearl"],
  "America/St_Kitts": ["Basseterre"],
  "America/St_Lucia": ["Gros Islet","Castries"],
  "America/St_Thomas": ["Saint Croix","Charlotte Amalie"],
  "America/St_Vincent": ["Kingstown","Calliaqua"],
  "America/Tegucigalpa": ["Tegucigalpa","San Pedro Sula","Danlí","La Ceiba"],
  "America/Thule": ["Thule"],
  "America/Tijuana": ["Tijuana","Mexicali","Ensenada","Rosarito"],
  "America/Toronto": ["Toronto","Montréal","Ottawa","Mississauga"],
  "America/Tortola": ["Road Town"],
  "America/Vancouver": ["Vancouver","Surrey","Victoria","Burnaby"],
  "America/Whitehorse": ["Whitehorse","Fort St. John","Creston","Dawson"],
  "America/Winnipeg": ["Winnipeg","Fort Garry South","Brandon","St. James-Assiniboia East"],
  "Antarctica/Casey": ["Casey"],
  "Antarctica/Davis": ["Davis"],
  "Antarctica/DumontDUrville": ["DumontDUrville"],
  "Antarctica/Mawson": ["Mawson","Vostok"],
  "Antarctica/McMurdo": ["McMurdo"],
  "Antarctica/Palmer": ["Palmer","Rothera"],
  "Antarctica/Syowa": ["Syowa"],
  "Antarctica/Troll": ["Troll"],
  "Arctic/Longyearbyen": ["Longyearbyen"],
  "Asia/Aden": ["Sanaa","Aden","Taiz","Ibb"],
  "Asia/Almaty": ["Almaty","Astana","Shymkent","Aktobe"],
  "Asia/Amman": ["Amman","Zarqa","Irbid","Russeifa"],
  "Asia/Ashgabat": ["Ashgabat","Türkmenabat","Daşoguz","Mary"],
  "Asia/Baghdad": ["Baghdad","Al Mawşil al Jadīdah","Mosul","Erbil"],
  "Asia/Bahrain": ["Al Muharraq","Manama","Madīnat Ḩamad","Ar Rifā‘"],
  "Asia/Baku": ["Baku","Sumgayit","Ganja","Khirdalan"],
  "Asia/Bangkok": ["Bangkok","Samut Prakan","Mueang Nonthaburi","Chon Buri"],
  "Asia/Beirut": ["Beirut","Ra’s Bayrūt","Tripoli","Sidon"],
  "Asia/Bishkek": ["Bishkek","Osh","Manas","Karakol"],
  "Asia/Brunei": ["Bandar Seri Begawan","Sengkurong","Mentiri","Kuala Belait"],
  "Asia/Chita": ["Chita","Yakutsk","Blagoveshchensk","Belogorsk"],
  "Asia/Colombo": ["Colombo","Dehiwala-Mount Lavinia","Maharagama","Jaffna"],
  "Asia/Damascus": ["Aleppo","Damascus","Homs","Latakia"],
  "Asia/Dhaka": ["Dhaka","Chattogram","Gazipur","Khulna"],
  "Asia/Dili": ["Dili","Maliana","Suai","Likisá"],
  "Asia/Dubai": ["Dubai","Abu Dhabi","Sharjah","Al Ain City"],
  "Asia/Dushanbe": ["Dushanbe","Isfara","Istaravshan","Kŭlob"],
  "Asia/Hebron": ["East Jerusalem","Gaza","Khān Yūnis","Jabālyā"],
  "Asia/Ho_Chi_Minh": ["Ho Chi Minh City","Cần Thơ","Da Nang","Biên Hòa"],
  "Asia/Hong_Kong": ["Hong Kong","New Territories","Kowloon","Hong Kong Island"],
  "Asia/Hovd": ["Ulaangom","Khovd","Ölgii","Altai"],
  "Asia/Irkutsk": ["Irkutsk","Ulan-Ude","Bratsk","Angarsk"],
  "Asia/Jakarta": ["Jakarta","Surabaya","Bekasi","Bandung"],
  "Asia/Jayapura": ["Jayapura","Ambon","Sorong","Ternate"],
  "Asia/Jerusalem": ["Jerusalem","Tel Aviv","West Jerusalem","Haifa"],
  "Asia/Kabul": ["Kabul","Herāt","Mazār-e Sharīf","Kandahār"],
  "Asia/Kamchatka": ["Petropavlovsk-Kamchatsky","Yelizovo","Vilyuchinsk","Anadyr"],
  "Asia/Karachi": ["Lahore","Karachi","Peshawar","Faisalabad"],
  "Asia/Kathmandu": ["Kathmandu","Pokhara","Bharatpur","Pātan"],
  "Asia/Kolkata": ["Mumbai","Delhi","Bengaluru","Hyderabad"],
  "Asia/Kuala_Lumpur": ["Kuala Lumpur","Johor Bahru","Kampung Baru Subang","Petaling Jaya"],
  "Asia/Kuwait": ["Al Aḩmadī","Ḩawallī","As Sālimīyah","Şabāḩ as Sālim"],
  "Asia/Macau": ["Macau","Taipa","Sé","Luhuan"],
  "Asia/Makassar": ["Makassar","Samarinda","Balikpapan","Denpasar"],
  "Asia/Manila": ["Quezon City","Davao","Caloocan","Manila"],
  "Asia/Muscat": ["Muscat","Seeb","Bawshar","‘Ibrī"],
  "Asia/Nicosia": ["Nicosia","Limassol","Larnaca","Stróvolos"],
  "Asia/Novosibirsk": ["Novosibirsk","Krasnoyarsk","Barnaul","Tomsk"],
  "Asia/Omsk": ["Omsk","Tara","Kalachinsk","Isil’kul’"],
  "Asia/Phnom_Penh": ["Phnom Penh","Takeo","Siem Reap","Battambang"],
  "Asia/Pyongyang": ["Pyongyang","Hamhŭng","Namp’o","Sunch’ŏn"],
  "Asia/Qatar": ["Doha","Ar Rayyān","Lusail","Al Maţār al ‘Atīq"],
  "Asia/Riyadh": ["Jeddah","Riyadh","Makkah","Madinah"],
  "Asia/Sakhalin": ["Yuzhno-Sakhalinsk","Magadan","Korsakov","Kholmsk"],
  "Asia/Seoul": ["Seoul","Busan","Incheon","Daegu"],
  "Asia/Shanghai": ["Shanghai","Chongqing","Chengdu","Beijing"],
  "Asia/Singapore": ["Singapore","Ulu Bedok","Bedok New Town","Sengkang New Town"],
  "Asia/Taipei": ["Taipei","New Taipei City","Taichung","Kaohsiung"],
  "Asia/Tashkent": ["Tashkent","Andijon","Namangan","Samarkand"],
  "Asia/Tbilisi": ["Tbilisi","Batumi","Kutaisi","Rustavi"],
  "Asia/Tehran": ["Tehran","Mashhad","Isfahan","Karaj"],
  "Asia/Thimphu": ["Thimphu","Phuntsholing","Tsirang","Punākha"],
  "Asia/Tokyo": ["Tokyo","Yokohama","Osaka","Nagoya"],
  "Asia/Ulaanbaatar": ["Ulan Bator","Erdenet","Darhan","Choibalsan"],
  "Asia/Urumqi": ["Ürümqi","Shihezi","Korla","Aqsu"],
  "Asia/Vientiane": ["Vientiane","Savannakhet","Thakhèk","Pakse"],
  "Asia/Vladivostok": ["Khabarovsk","Vladivostok","Komsomolsk-on-Amur","Ussuriysk"],
  "Asia/Yangon": ["Yangon","Mandalay","Nay Pyi Taw","Hlaingthaya"],
  "Asia/Yekaterinburg": ["Yekaterinburg","Chelyabinsk","Ufa","Perm"],
  "Asia/Yerevan": ["Yerevan","Malatia-Sebastia","Shengavit","Nor Nork"],
  "Atlantic/Azores": ["Ponta Delgada"],
  "Atlantic/Bermuda": ["Hamilton"],
  "Atlantic/Canary": ["Las Palmas de Gran Canaria","Santa Cruz de Tenerife","La Laguna","Telde"],
  "Atlantic/Cape_Verde": ["Praia","Mindelo","Espargos","Assomada"],
  "Atlantic/Faroe": ["Tórshavn"],
  "Atlantic/Reykjavik": ["Reykjavík","Kópavogur","Hafnarfjörður","Reykjanesbær"],
  "Atlantic/South_Georgia": ["Grytviken"],
  "Atlantic/St_Helena": ["Jamestown"],
  "Atlantic/Stanley": ["Stanley"],
  "Australia/Adelaide": ["Adelaide","Adelaide Hills","Mount Gambier","Morphett Vale"],
  "Australia/Brisbane": ["Brisbane","Gold Coast","Sunshine Coast","Logan City"],
  "Australia/Darwin": ["Darwin","Palmerston","Alice Springs"],
  "Australia/Eucla": ["Eucla"],
  "Australia/Lord_Howe": ["Lord Howe"],
  "Australia/Perth": ["Perth","Mandurah","Bunbury","Geraldton"],
  "Australia/Sydney": ["Sydney","Melbourne","Newcastle","Canberra"],
  "Europe/Amsterdam": ["Rotterdam","Amsterdam","The Hague","Utrecht"],
  "Europe/Andorra": ["Andorra la Vella","les Escaldes"],
  "Europe/Athens": ["Athens","Thessaloníki","Pátra","Piraeus"],
  "Europe/Belgrade": ["Belgrade","Niš","Novi Sad","Novi Beograd"],
  "Europe/Berlin": ["Berlin","Hamburg","Munich","Köln"],
  "Europe/Bratislava": ["Bratislava","Košice","Petržalka","Nitra"],
  "Europe/Brussels": ["Brussels","Antwerp","Gent","Charleroi"],
  "Europe/Bucharest": ["Bucharest","Sector 3","Iaşi","Sector 6"],
  "Europe/Budapest": ["Budapest","Pest","Buda","Debrecen"],
  "Europe/Chisinau": ["Chisinau","Tiraspol","Bălţi","Bender"],
  "Europe/Copenhagen": ["Copenhagen","Århus","Odense","Aalborg"],
  "Europe/Dublin": ["Dublin","South Dublin","Cork","Limerick"],
  "Europe/Gibraltar": ["Gibraltar"],
  "Europe/Guernsey": ["Saint Peter Port"],
  "Europe/Helsinki": ["Helsinki","Espoo","Tampere","Vantaa"],
  "Europe/Isle_of_Man": ["Douglas"],
  "Europe/Istanbul": ["Istanbul","Ankara","Bursa","İzmir"],
  "Europe/Jersey": ["Saint Helier"],
  "Europe/Kaliningrad": ["Kaliningrad","Chernyakhovsk","Sovetsk","Baltiysk"],
  "Europe/Kyiv": ["Kyiv","Kharkiv","Odesa","Dnipro"],
  "Europe/Lisbon": ["Lisbon","Porto","Braga","Amadora"],
  "Europe/Ljubljana": ["Ljubljana","Maribor","Celje","Kranj"],
  "Europe/London": ["London","Birmingham","Glasgow","Manchester"],
  "Europe/Luxembourg": ["Luxembourg","Esch-sur-Alzette","Dudelange"],
  "Europe/Madrid": ["Madrid","Barcelona","Valencia","Zaragoza"],
  "Europe/Malta": ["San Pawl il-Baħar","Birkirkara","Mosta","Sliema"],
  "Europe/Mariehamn": ["Mariehamn"],
  "Europe/Minsk": ["Minsk","Homyel'","Hrodna","Vitebsk"],
  "Europe/Monaco": ["Monaco","Monte-Carlo"],
  "Europe/Moscow": ["Moscow","Saint Petersburg","Nizhniy Novgorod","Kazan"],
  "Europe/Oslo": ["Oslo","Bergen","Trondheim","Stavanger"],
  "Europe/Paris": ["Paris","Marseille","Lyon","Toulouse"],
  "Europe/Podgorica": ["Podgorica","Nikšić","Herceg Novi","Pljevlja"],
  "Europe/Prague": ["Prague","Brno","Ostrava","Pilsen"],
  "Europe/Riga": ["Riga","Daugavpils","Liepāja","Jelgava"],
  "Europe/Rome": ["Rome","Milan","Naples","Turin"],
  "Europe/Samara": ["Samara","Saratov","Tolyatti","Izhevsk"],
  "Europe/San_Marino": ["San Marino"],
  "Europe/Sarajevo": ["Sarajevo","Banja Luka","Zenica","Tuzla"],
  "Europe/Simferopol": ["Sevastopol","Simferopol","Kerch","Yevpatoriya"],
  "Europe/Skopje": ["Skopje","Kumanovo","Prilep","Bitola"],
  "Europe/Sofia": ["Sofia","Plovdiv","Varna","Burgas"],
  "Europe/Stockholm": ["Stockholm","Gothenburg","Malmö","Uppsala"],
  "Europe/Tallinn": ["Tallinn","Lasnamäe","Tartu","Mustamäe"],
  "Europe/Tirane": ["Tirana","Durrës","Vlorë","Elbasan"],
  "Europe/Vaduz": ["Vaduz"],
  "Europe/Vatican": ["Vatican City"],
  "Europe/Vienna": ["Vienna","Graz","Linz","Favoriten"],
  "Europe/Vilnius": ["Vilnius","Kaunas","Klaipėda","Šiauliai"],
  "Europe/Warsaw": ["Warsaw","Kraków","Wrocław","Łódź"],
  "Europe/Zagreb": ["Zagreb","Split","Rijeka","Osijek"],
  "Europe/Zurich": ["Zürich","Geneva","Basel","Lausanne"],
  "Indian/Antananarivo": ["Antananarivo","Toamasina","Antsirabe","Mahajanga"],
  "Indian/Chagos": ["Chagos"],
  "Indian/Christmas": ["Flying Fish Cove"],
  "Indian/Cocos": ["West Island"],
  "Indian/Comoro": ["Moroni","Moutsamoudou","Fomboni"],
  "Indian/Kerguelen": ["Port-aux-Français"],
  "Indian/Mahe": ["Victoria"],
  "Indian/Maldives": ["Male"],
  "Indian/Mauritius": ["Port Louis","Vacoas","Beau Bassin-Rose Hill","Curepipe"],
  "Indian/Mayotte": ["Mamoudzou","Koungou","Labattoir","Kaouéni"],
  "Indian/Reunion": ["Saint-Denis","Saint-Paul","Saint-Pierre","Le Tampon"],
  "Pacific/Apia": ["Apia"],
  "Pacific/Auckland": ["Auckland","Christchurch","Wellington","Manukau City"],
  "Pacific/Bougainville": ["Arawa"],
  "Pacific/Chatham": ["Chatham"],
  "Pacific/Chuuk": ["Chuuk"],
  "Pacific/Easter": ["Easter"],
  "Pacific/Efate": ["Port-Vila"],
  "Pacific/Fakaofo": ["Fakaofo"],
  "Pacific/Fiji": ["Nasinu","Suva","Lautoka","Nadi"],
  "Pacific/Funafuti": ["Funafuti"],
  "Pacific/Galapagos": ["Galapagos"],
  "Pacific/Gambier": ["Gambier"],
  "Pacific/Guadalcanal": ["Honiara","Panatina","Nggosi","Tandai"],
  "Pacific/Guam": ["Dededo Village","Yigo Village","Tamuning-Tumon-Harmon Village","Tamuning"],
  "Pacific/Honolulu": ["Honolulu","East Honolulu","Pearl City","Waiau-Pacific Palisades"],
  "Pacific/Kanton": ["Kanton"],
  "Pacific/Kiritimati": ["Kiritimati"],
  "Pacific/Kosrae": ["Kosrae","Palikir"],
  "Pacific/Majuro": ["Majuro","Dalap-Uliga-Dorrit","Kwajalein"],
  "Pacific/Marquesas": ["Marquesas"],
  "Pacific/Midway": ["Midway"],
  "Pacific/Nauru": ["Yaren"],
  "Pacific/Niue": ["Alofi"],
  "Pacific/Norfolk": ["Kingston"],
  "Pacific/Noumea": ["Nouméa","Mont-Dore","Dumbéa"],
  "Pacific/Pago_Pago": ["Pago Pago"],
  "Pacific/Palau": ["Ngerulmud"],
  "Pacific/Pitcairn": ["Adamstown"],
  "Pacific/Port_Moresby": ["Port Moresby","Lae","Mount Hagen","Popondetta"],
  "Pacific/Rarotonga": ["Avarua"],
  "Pacific/Saipan": ["Saipan"],
  "Pacific/Tahiti": ["Faaa","Papeete","Punaauia"],
  "Pacific/Tarawa": ["Tarawa"],
  "Pacific/Tongatapu": ["Nuku‘alofa"],
  "Pacific/Wake": ["Wake"],
  "Pacific/Wallis": ["Mata-Utu"],
};
