// src/content/alphaCatalogue.test.ts
//
// The alpha catalogue is generated by scripts/alpha-catalogue.mjs and committed. This suite is
// the assertion that the committed copy still describes the tree: a key added to a screen with no
// part to hold it fails here rather than going missing from a review page.
//
// ?raw rather than node:fs because tsconfig.app.json pins `types` to the vite client types, the
// convention src/domain/schedule/cursor.test.ts already uses.
import { describe, expect, it } from 'vitest';

import catalogueJson from '../../docs/feedback/catalogue.json?raw';
import { DEFAULT_COPY } from './copy';

interface CatalogueKey {
  key: string;
  default: string;
  limelight: string;
  board: string;
  isControl: boolean;
  limelightRowPermitted: boolean;
  refusalGroup: string | null;
}

interface CataloguePart {
  id: string;
  screen: string;
  order: number;
  title: string;
  what: string;
  components: string[];
  states: string[];
  keys: CatalogueKey[];
  status: string;
}

interface Catalogue {
  generatedFrom: string;
  counts: { screens: number; parts: number; keys: number; notRendered: number; table: number };
  parts: CataloguePart[];
  notRendered: { key: string; reason: string }[];
}

const catalogue = JSON.parse(catalogueJson) as Catalogue;
const live = catalogue.parts.filter((p) => p.status === 'live');

/** Two or three hyphen-lower-case segments. Decision alpha-feedback-part-ids. */
const ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*(?:\.[a-z0-9]+(?:-[a-z0-9]+)*){1,2}$/;

const SCREENS = [
  'intro',
  'boot',
  'shell',
  'setup',
  'today',
  'train',
  'plan',
  'targets',
  'log',
  'atlas',
  'settings',
  'install',
  'popup',
  'toast',
];

describe('the alpha catalogue', () => {
  it('states its part count, and holds it', () => {
    // P10 Brief C added two: intro.sequence and intro.skip, the same shape as boot.sequence and
    // boot.skip, for the intro sequence shown once ahead of the boot sequence. P10 Brief D added
    // one more: shell.footer, for the site footer at the foot of the app shell.
    //
    // ROUND 2, BRIEF J removed intro.skip, taking the count from 102 to 101. The owner asked for
    // the intro's Skip control to go (r2.01): `ui.introSeen` already stops the sequence returning,
    // so the control only ever let a first-time reader skip the caveats, which is the one thing it
    // must not do. boot.skip is a DIFFERENT part on a different screen and still ships.
    expect(catalogue.counts.parts).toBe(101);
    expect(live).toHaveLength(101);
  });

  it('gives every part an id in the grammar, under a known screen', () => {
    for (const part of catalogue.parts) {
      expect(ID_RE.test(part.id), part.id).toBe(true);
      expect(SCREENS).toContain(part.screen);
      expect(part.id.startsWith(`${part.screen}.`), part.id).toBe(true);
    }
  });

  it('assigns every key to exactly one part', () => {
    const homes = new Map<string, string[]>();
    for (const part of live) {
      for (const k of part.keys) {
        const list = homes.get(k.key) ?? [];
        list.push(part.id);
        homes.set(k.key, list);
      }
    }
    const shared = [...homes.entries()].filter(([, ids]) => ids.length > 1);
    expect(shared).toEqual([]);
  });

  it('leaves no key unassigned on any screen', () => {
    const leftovers = catalogue.parts
      .filter((p) => p.id.endsWith('.unassigned'))
      .filter((p) => p.keys.length > 0)
      .map((p) => `${p.id}: ${p.keys.map((k) => k.key).join(', ')}`);
    expect(leftovers).toEqual([]);
  });

  it('places every key in DEFAULT_COPY exactly once, or excuses it by name', () => {
    const placed = new Set(live.flatMap((p) => p.keys.map((k) => k.key)));
    const excused = new Set(catalogue.notRendered.map((n) => n.key));
    const table = Object.keys(DEFAULT_COPY);
    const missing = table.filter((k) => !placed.has(k) && !excused.has(k));
    expect(missing).toEqual([]);
    const both = [...excused].filter((k) => placed.has(k));
    expect(both).toEqual([]);
    expect(placed.size + excused.size).toBe(table.length);
    expect(catalogue.counts.table).toBe(table.length);
  });

  it('quotes the default string the table holds, byte for byte', () => {
    for (const part of live) {
      for (const k of part.keys) {
        expect(DEFAULT_COPY[k.key as keyof typeof DEFAULT_COPY], k.key).toBe(k.default);
      }
    }
  });

  it('names a refusal group for every control that may not take a limelight row', () => {
    for (const part of live) {
      for (const k of part.keys) {
        if (k.limelightRowPermitted) {
          expect(k.refusalGroup, k.key).toBeNull();
        } else {
          expect(typeof k.refusalGroup, k.key).toBe('string');
          expect(k.limelight, k.key).toBe('same');
        }
      }
    }
  });
});
