// scripts/alpha-parts.mjs
//
// The authored half of the alpha catalogue: one record per reviewable part of the app, in the
// order the owner meets it. Data only; scripts/alpha-catalogue.mjs joins it to the tree.
//
// THE ONE RULE FOR ADDING A PART. An id is assigned once and never renamed, because every comment
// the owner has ever filed is keyed by it. A part that leaves the app keeps its record and takes
// status: 'retired'. See docs/plans/2026-09-02-10-alpha-feedback-loop.md, decision
// alpha-feedback-part-ids.
//
// `keys` is optional. Omit it and the part takes every copy key its `components` mention that no
// earlier part, on this screen or an earlier one, has claimed. State it where several parts share
// one file, which is every view that draws more than one section. State `keys: []` where a part
// draws no string of its own but must not sweep its file either.
//
// ONE CLAIM MAP SPANS THE WHOLE TREE. A key rendered on several screens is filed under the first
// screen in app order that renders it, so a control the setup wizard previews and the Targets
// view repeats is catalogued once, under setup. That is why several parts below hold no key.

/** @typedef {{id:string,title:string,what:string,screen:string,components:string[],states:string[],keys?:string[],status?:string}} Part */

/** @type {Part[]} */
export const PARTS = [
  // --- intro, shown once ahead of boot (P10 Brief C) ---
  // EXPLICIT `keys`, and it must stay explicit. IntroSequence.tsx also renders `button.continue`,
  // which `setup.nav` owns. The intro screen is swept before the setup screen, so a part here with
  // no `keys` array claims that shared key first and setup.nav then collides with it -- the same
  // hazard the two-pass comment in alpha-catalogue.mjs records for boot.sequence and
  // button.skipBoot. Listing this part's own key leaves button.continue for setup.nav to claim.
  // Round 2, brief J: the acknowledgement modal is what introduced the shared control here.
  // Round 3: `label.changeVisualSettings` added -- the caption on the arrow the final slide
  // draws at the shell's skin-and-preferences control, added to this part's own explicit `keys`
  // for the reason stated above rather than left to auto-derive.
  { id: 'intro.sequence', title: 'Intro sequence', what: 'The caveat slides, and the tl;dr acknowledgement modal that gates the end of the sequence.', screen: 'intro', components: ['src/ui/intro/IntroSequence.tsx'], states: ['running', 'finished', 'final-slide'], keys: ['advice.clickToContinue', 'button.introContinue', 'label.changeVisualSettings'] },

  // --- boot ---
  { id: 'boot.sequence', title: 'Boot sequence', what: 'The dotted step lines that print on the first open.', screen: 'boot', components: ['src/ui/components/Boot.tsx'], states: ['running', 'finished'] },
  { id: 'boot.skip', title: 'Skip control', what: 'The control that ends the sequence, and the any-key skip.', screen: 'boot', components: ['src/ui/components/Boot.tsx'], states: ['visible'], keys: ['button.skipBoot'] },

  // --- shell ---
  // P10 Brief D: the status word moved off this bar entirely (to shell.footer, below), and the
  // fixed brand now sits beside a per-view instruction that moves on limelight and board and
  // sits still, as plain text, on clinical (Marquee.tsx renders nothing there by design).
  // Round 2 brief N adds two things to this bar and both are filed here rather than under new
  // part ids, because both of the owner's comments about them (r2.05 and r2-onboarding.general)
  // are already filed against `shell.topbar`: the banner that names where you are, and the skin
  // control that is the only route to the picker while setup is running.
  { id: 'shell.topbar', title: 'Top bar', what: 'The fixed brand, the banner naming where the user is, the moving instruction for the current view, and the setup-only skin control.', screen: 'shell', components: ['src/app/App.tsx', 'src/ui/components/Marquee.tsx', 'src/ui/setup/setupBanner.tsx'], states: ['scrolling', 'static-fallback', 'intro', 'setup', 'setup-named', 'setup-anonymous'], keys: ['advice.todayInstruction', 'advice.planInstruction', 'advice.trainInstruction', 'advice.targetsInstruction', 'advice.logInstruction', 'advice.atlasInstruction', 'advice.settingsInstruction', 'button.pauseUpdates', 'advice.setupInstruction', 'status.bannerIntro', 'status.bannerSetup', 'status.bannerSetupNamed', 'status.bannerSetupAnonymous', 'disclosure.skin'] },
  { id: 'shell.session-indicator', title: 'Session indicator', what: 'The plan position, read a second time as its own marquee item in shell.topbar (P10 Brief D); the standalone component is unrendered but still tested on its own.', screen: 'shell', components: ['src/ui/components/SessionIndicator.tsx'], states: ['no-plan', 'idle', 'in-progress'], keys: ['hero.programmeComplete', 'label.planPosition', 'status.planComplete', 'status.sessionCursor'] },
  // P10 Brief D: `shell.status.loaded` / `shell.status.loading` moved here from shell.topbar, and
  // `advice.dataOnDevice` moved here from settings.data.on-device -- both because the footer,
  // mounted once at the foot of the shell, is now the first screen in app order that renders
  // either, which is where the whole-tree claim map files a key rendered on more than one screen.
  { id: 'shell.footer', title: 'Site footer', what: 'The author, the repository, the version and build, the last update, the hydration status, the on-device promise, the disclaimer and the licence, once at the foot of every screen.', screen: 'shell', components: ['src/ui/components/SiteFooter.tsx'], states: ['default'], keys: ['shell.status.loaded', 'shell.status.loading', 'advice.dataOnDevice', 'footer.builtBy', 'footer.repository', 'footer.version', 'footer.updated', 'footer.licence'] },
  { id: 'shell.tab-strip', title: 'Tab strip', what: 'The seven tabs, in the order src/ui/nav/views.ts sets.', screen: 'shell', components: ['src/app/App.tsx', 'src/ui/nav/views.ts'], states: ['default'], keys: ['nav.atlas', 'nav.label', 'nav.log', 'nav.plan', 'nav.settings', 'nav.targets', 'nav.today', 'nav.train'] },
  { id: 'shell.spotlight-button', title: 'Spotlight button', what: 'The control that opens the command palette.', screen: 'shell', components: ['src/ui/components/SpotlightButton.tsx'], states: ['default'] },
  { id: 'shell.update-prompt', title: 'Update prompt', what: 'The banner offering a reload when a new build is waiting.', screen: 'shell', components: ['src/app/UpdatePrompt.tsx'], states: ['hidden', 'offered'] },
  { id: 'shell.save-error', title: 'Save error banner', what: 'The banner shown when the document could not be written.', screen: 'shell', components: ['src/app/App.tsx'], states: ['hidden', 'raised'], keys: ['banner.saveFailed.body', 'banner.saveFailed.tag', 'banner.saveQuota.body', 'banner.saveQuota.tag', 'banner.saveUnavailable.body', 'banner.saveUnavailable.tag', 'button.exportData', 'button.exportStoredCopy', 'button.retrySave'] },
  { id: 'shell.load-error', title: 'Load error banner', what: 'The banner shown when the stored document could not be read.', screen: 'shell', components: ['src/app/App.tsx'], states: ['hidden', 'raised'], keys: ['banner.loadInvalid.body', 'banner.loadInvalid.tag', 'button.exportStoredData'] },

  // --- setup, nine steps in the order src/ui/setup/SetupWizard.tsx sets ---
  { id: 'setup.progress', title: 'Step counter', what: 'The "step N of 9" line and the step title above every screen.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default'], keys: ['setup.hero', 'group.settings', 'group.personal', 'group.goal'] },
  { id: 'setup.units', title: 'Step 1, Units', what: 'Metric or imperial, and what the choice does to stored values.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default'], keys: ['advice.unitsOnce', 'label.units', 'label.unitsImperial', 'label.unitsMetric', 'step.units'] },
  // Round 2 r2.09: the list is grouped by year-round behaviour and sorted by offset, the search
  // reads every zone the platform has, and a bordered box below the field says what the answer
  // is for. src/domain/dates.ts is listed as a component because the rows, their order and
  // their labels are all produced there rather than here.
  { id: 'setup.timezone', title: 'Step 2, Time zone', what: 'The zone every civil date in the app is computed in, chosen from a list grouped by year-round behaviour and ordered by offset, searchable across every zone the platform knows.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx', 'src/domain/dates.ts'], states: ['default', 'searching', 'no-match'], keys: ['advice.timezoneDetected', 'advice.timezonePick', 'advice.timezoneInvalid', 'advice.timezoneGrouped', 'advice.timezoneNoMatch', 'label.timezone', 'label.timezoneSearch', 'status.timezoneAlso', 'hero.timezoneWhy', 'label.timezoneDayBoundary', 'advice.timezoneDayBoundary', 'label.timezoneReminders', 'advice.timezoneReminders', 'step.timezone'] },
  { id: 'setup.body', title: 'Step 3, Body', what: 'Body mass, stature, age, sex, the methods list, and the optional tape estimate.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default', 'blocked'], keys: ['advice.bodyFatEstimate', 'advice.bodyFatOptional', 'advice.bodyFatRequiredND', 'advice.estimateBodyFat', 'advice.sexDeselect', 'advice.sexWorkaround', 'advice.tapeMethod', 'advice.tapeNeedFemale', 'advice.tapeNeedMale', 'advice.tapeNeedsSex', 'advice.tapeOutOfDomain', 'button.closeModal', 'disclosure.disclaimer', 'disclosure.references', 'error.positive', 'error.valueRequired', 'error.wholeNumber', 'label.bodyFat', 'label.bodyFatChart', 'label.bodyFatEstimate', 'label.bodyFatKnown', 'label.bodyFatNone', 'label.bodyFatTape', 'label.needsBiologicalSex', 'label.weighIn', 'advice.weighIn', 'advice.weighInReassurance', 'label.centimetres', 'label.feet', 'label.inches', 'label.metres', 'label.name', 'label.sex', 'label.sexFemale', 'label.sexMale', 'label.sexNotDisclosed', 'label.sexRationale', 'quantity.abdomenI', 'quantity.abdomenII', 'quantity.age', 'quantity.bodyFat', 'quantity.bodyMass', 'quantity.height', 'quantity.hip', 'quantity.neck', 'step.body', 'why.bodyFatEstimate'] },
  // Brief G adds two keys: advice.activityLevelsSource (the "Where These Levels Come From" link)
  // and label.activityLevelsSource (the modal's own heading it opens). button.closeModal is NOT
  // added here even though that modal renders it too: setup.body (step 3) already claims it for
  // the sex explainer, the first screen in app order that renders it, per this file's own
  // one-claim-map-spans-the-tree rule above.
  { id: 'setup.training', title: 'Step 4, Equipment & Availability', what: 'Everyday activity and equipment access as sliders with stop markers, gym comfort as three option boxes, the equipment questions the equipment access slider reveals, and the two load increments below them (round 3 Tasks 5 to 8).', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default', 'walk-to-gym', 'home-equipment', 'bodyweight-equipment'], keys: ['advice.activityLevelsSource', 'advice.equipmentInventoryPrompt', 'advice.loadSteps', 'advice.walkToGym', 'button.no', 'button.yes', 'disclosure.examples', 'label.activity', 'label.activityLevelsSource', 'label.equipmentAccess', 'label.experience', 'label.homeEquipmentAerobic', 'label.homeEquipmentDumbbells', 'label.homeEquipmentMachines', 'option.accessBodyweight', 'option.accessFullAndHome', 'option.accessFullGym', 'option.accessHome', 'option.accessHomeAndBodyweight', 'option.activityModerate', 'option.activitySedentary', 'option.activityVigorous', 'option.bodyweightPullUpBar', 'option.bodyweightResistanceBands', 'option.bodyweightSkippingRope', 'option.bodyweightYogaMat', 'option.experienceAdvanced', 'option.experienceIntermediate', 'option.experienceNovice', 'option.homeBench', 'option.homeCableMachine', 'option.homeElliptical', 'option.homeLatPulldown', 'option.homeLegPress', 'option.homeRowingMachine', 'option.homeSmithMachine', 'option.homeSquatRack', 'option.homeTreadmill', 'quantity.barbellStep', 'quantity.dumbbellStep', 'label.loadStep', 'quantity.walkMinutes', 'step.training'] },
  // Brief I Parts 1, 2 and 4. `disclosure.why` renders on this step too (the recomposition cost
  // and the body-fat-target basis both sit behind one) and is deliberately NOT listed here: it
  // is already claimed by setup.review, and a key may be claimed by exactly one part.
  { id: 'setup.goal', title: 'Step 5, Fitness Goal', what: 'The two axes the goal is derived from, the body-fat or body-mass target, and the target date with its feasibility calendar (Brief I).', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default', 'recomposition', 'no-bodyfat-estimate'], keys: ['advice.feasibilityEstimate', 'advice.feasibilityMassHeld', 'advice.feasibilityNeedsFuture', 'advice.feasibilityNeedsTarget', 'advice.feasibilityNotALoss', 'advice.feasibilityNoWeeklyRate', 'advice.feasibilityRate', 'advice.feasibilitySlow', 'advice.goalOutcomeFatLoss', 'advice.goalOutcomeMaintenance', 'advice.goalOutcomeMuscleGain', 'advice.goalOutcomeRecomposition', 'advice.goalRecompositionCost', 'advice.impliedComposition', 'advice.targetBodyFatBasis', 'advice.targetBodyFatUnavailable', 'button.nextMonth', 'button.previousMonth', 'label.fatAxis', 'label.feasibility', 'label.goal', 'label.muscleAxis', 'label.targetDate', 'option.fatHold', 'option.fatLose', 'option.goalFatLoss', 'option.goalMaintenance', 'option.goalMuscleGain', 'option.goalRecomposition', 'option.muscleGain', 'option.muscleHold', 'quantity.targetBodyFat', 'quantity.targetBodyMass', 'status.bandHighlyImprobable', 'status.bandImprobable', 'status.bandRealistic', 'step.goal'] },
  // Availability is no longer a step of its own: finding B43 folded these controls into the
  // training step so the weekly slots are stated BEFORE the target date. The part survives as a
  // named group of controls on that step, and `step.availability` is gone with the heading.
  { id: 'setup.availability', title: 'Step 5, Availability', what: 'The days and times you can train, stated at the top of the goal step, above the target date the feasibility calendar assesses (round 3 Task 9).', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default'], keys: ['error.pickOneDay', 'label.duration', 'label.sessionsPerWeek', 'label.startTime', 'quantity.weeklySessionTarget', 'weekday.friday', 'weekday.monday', 'weekday.saturday', 'weekday.sunday', 'weekday.thursday', 'weekday.tuesday', 'weekday.wednesday'] },
  { id: 'setup.programme', title: 'Step 7, Programme length', what: 'How many weeks the generated plan runs for.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default'], keys: ['advice.deloadEveryFourth', 'label.includeCardio', 'quantity.programmeWeeks', 'step.programme'] },
  // 'label.caution' is a pre-existing gap fixed in passing while regenerating for Brief B: it
  // reads GuidanceScreen.tsx (screen order puts setup before train, so it wins the claim over
  // FormCuesModal.tsx's identical string, per "the first screen in app order that renders it").
  { id: 'setup.guidance', title: 'Step 8, Guidance', what: 'Supplement and kit guidance, inside the wizard.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx', 'src/ui/setup/GuidanceScreen.tsx'], states: ['default'], keys: ['hero.guidance', 'label.caution', 'step.guidance'] },
  { id: 'setup.review', title: 'Step 9, Review', what: 'The summary, and the control that writes the profile.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['ready', 'blocked'], keys: ['advice.beverageRange', 'advice.creatineOnly', 'label.creatine', 'button.confirmStart', 'disclosure.why', 'hero.dailyTargets', 'hero.programme', 'hero.yourData', 'label.creatineDose', 'label.energy', 'label.expectedRate', 'label.fluid', 'label.inTargetRange', 'label.looksGood', 'label.maintenanceOnly', 'label.none', 'label.protein', 'status.rateUnknown', 'status.targetsNotEstimated', 'step.review', 'hero.yourAnswers'] },
  { id: 'setup.nav', title: 'Wizard navigation', what: 'Back and Continue, and what a blocked step does to them.', screen: 'setup', components: ['src/ui/setup/SetupWizard.tsx'], states: ['default', 'blocked'], keys: ['button.back', 'button.continue'] },

  // --- today ---
  { id: 'today.marquee', title: 'Marquee', what: 'The scrolling ticker strip at the top of Today.', screen: 'today', components: ['src/ui/components/Marquee.tsx', 'src/ui/format/weekDelta.ts'], states: ['scrolling', 'reduced-motion'], keys: ['button.pauseTicker', 'status.weekDeltaNegative', 'status.weekDeltaPositive', 'status.weekDeltaZero'] },
  { id: 'today.refusal-banner', title: 'Refusal banner', what: 'The line that reports why a control was refused, and its dismiss.', screen: 'today', components: ['src/ui/views/TodayView.tsx', 'src/ui/format/refusal.ts'], states: ['hidden', 'raised'], keys: ['banner.actionRefused.tag', 'button.dismiss', 'status.refusalAlreadyStarted', 'status.refusalLabelNotOffered', 'status.refusalNotNextDay', 'status.refusalPaused', 'status.refusalSessionOpen', 'status.refusalUnrecognised'] },
  { id: 'today.hero', title: 'Hero line', what: 'The one line Today is about, and the eyebrow above it.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['no-plan', 'scheduled', 'in-progress', 'paused', 'skipped', 'completed', 'rest-day'], keys: ['advice.completeSetup', 'advice.nextSession', 'advice.noSessionIn14Days', 'hero.noPlan', 'hero.noSessionToday', 'hero.sessionCompleted', 'hero.sessionInProgress', 'hero.sessionSkipped'] },
  { id: 'today.session-card', title: 'Session card', what: 'The exercise list for today, with sets, reps and rest.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['scheduled', 'rest-day'], keys: ['status.setsBy'] },
  { id: 'today.start', title: 'Start control', what: 'The control that opens the session.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['enabled', 'in-progress'], keys: ['button.returnToSession', 'button.startSession'] },
  { id: 'today.mark-completed', title: 'Mark completed control', what: 'The control that closes today session without opening it.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['offered', 'hidden'], keys: ['button.markCompleted'] },
  { id: 'today.label-picker', title: 'Label picker', what: 'The control that trades today session for another label the week still owes.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['closed', 'open'], keys: ['button.trainLabelToday', 'button.trainSomethingElse', 'status.remainingThisWeek'] },
  { id: 'today.week-stamp', title: 'Week stamp', what: 'The stamp a week at or above its target earns.', screen: 'today', components: ['src/ui/components/WeekStamp.tsx'], states: ['hidden', 'stamped'] },
  { id: 'today.intervention', title: 'Intervention', what: 'The missed-week panel on Today, not the popup.', screen: 'today', components: ['src/ui/components/Intervention.tsx'], states: ['hidden', 'raised'] },
  { id: 'today.time-capsule', title: 'Time capsule', what: 'The capsule entry point on Today.', screen: 'today', components: ['src/ui/components/TimeCapsule.tsx'], states: ['none', 'sealed', 'openable', 'opened'], keys: ['advice.capsuleOpenDatePassed', 'advice.timeCapsule', 'button.openCapsule', 'button.readCapsule', 'button.writeCapsule', 'hero.timeCapsule', 'status.capsuleSealed', 'status.capsuleWritten'] },
  { id: 'today.strip', title: 'Fourteen-day strip', what: 'The fourteen day glyphs and their accessible names.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['planned', 'live', 'served', 'no-show', 'on-hiatus', 'off'], keys: ['hero.nextFourteenDays', 'status.dayCompleted', 'status.dayInProgress', 'status.dayPaused', 'status.dayPlanned', 'status.dayRest', 'status.daySkipped'] },
  { id: 'today.pause', title: 'Pause control', what: 'The control that stops the plan, and the paused line.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['pausable', 'paused'], keys: ['advice.pauseHoldsCursor', 'button.pausePlan', 'button.resumePlan', 'status.planPaused'] },
  { id: 'today.skip', title: 'Skip control', what: 'The skip control and its optional reason field.', screen: 'today', components: ['src/ui/views/TodayView.tsx'], states: ['closed', 'open', 'skipped'], keys: ['button.cancel', 'button.confirmSkip', 'button.skipToday', 'label.skipReason', 'status.skipReason'] },

  // --- train ---
  { id: 'train.header', title: 'Session header', what: 'The session name, the eyebrow and the deload note.', screen: 'train', components: ['src/ui/views/TrainView.tsx'], states: ['no-profile', 'no-session', 'in-progress'], keys: ['advice.deloadBlock', 'advice.noProfileTrain', 'advice.noSessionToday', 'hero.train', 'status.sessionEyebrow'] },
  { id: 'train.exercise-card', title: 'Exercise card', what: 'One exercise, its prescription and its suggested load.', screen: 'train', components: ['src/ui/views/train/ExerciseCard.tsx'], states: ['pending', 'active', 'done'], keys: ['button.addSet', 'button.formCues', 'button.formReference', 'label.noSuggestedLoad', 'label.suggestedLoad', 'status.adviceAddLoad', 'status.adviceDeload', 'status.adviceExtendReps', 'status.adviceHold', 'status.lastSessionSets'] },
  { id: 'train.set-row', title: 'Set row', what: 'One set: load, reps, the log control and the delete.', screen: 'train', components: ['src/ui/views/train/SetRow.tsx'], states: ['planned', 'logged', 'bonus'], keys: ['advice.durationNeeded', 'button.deleteSet', 'button.logSet', 'coach.setDeleted', 'label.bonusSet', 'status.setCounter'] },
  { id: 'train.rest-panel', title: 'Rest panel', what: 'The rest countdown, the extend control and the skip.', screen: 'train', components: ['src/ui/views/train/RestTimerPanel.tsx'], states: ['hidden', 'running', 'elapsed'], keys: ['button.extendRest', 'button.skipRest', 'notification.restOver', 'status.rest', 'status.restRemaining'] },
  { id: 'train.hydration-banner', title: 'Hydration banner', what: 'The beverage intake cue and its log control.', screen: 'train', components: ['src/ui/views/train/HydrationBanner.tsx', 'src/domain/training/hydration.ts'], states: ['hidden', 'shortfall', 'met'], keys: ['advice.beverageShortfall', 'advice.drinkToThirst', 'advice.logPostSessionMass', 'button.logVolume', 'why.postSessionMass'] },
  { id: 'train.add-custom-exercise', title: 'Add custom exercise', what: 'The form that adds an exercise the plan does not carry.', screen: 'train', components: ['src/ui/views/train/AddCustomExercise.tsx'], states: ['closed', 'open', 'refused'] },
  { id: 'train.body-mass-quick-log', title: 'Body mass quick log', what: 'The pre- and post-session body mass entry.', screen: 'train', components: ['src/ui/views/train/BodyMassQuickLog.tsx'], states: ['empty', 'logged', 'fluid-loss'], keys: ['advice.fluidLoss', 'button.logBodyMass', 'quantity.postSessionBodyMass', 'quantity.preSessionBodyMass', 'why.fluidLoss'] },
  { id: 'train.completion', title: 'Session completion', what: 'The finish control and the line that follows it.', screen: 'train', components: ['src/ui/views/TrainView.tsx'], states: ['incomplete', 'complete'], keys: ['button.backToToday', 'button.finishSession'] },

  // --- plan ---
  { id: 'plan.block-strip', title: 'Block strip', what: 'The training and deload blocks, with their session ranges.', screen: 'plan', components: ['src/ui/views/PlanView.tsx'], states: ['training', 'deload'], keys: ['label.block', 'label.blockStrip', 'status.blockSessions', 'status.deloadNote', 'status.deloadTag', 'why.deloadSets'] },
  { id: 'plan.week-scrubber', title: 'Week scrubber', what: 'The control that moves the view a week at a time.', screen: 'plan', components: ['src/ui/views/PlanView.tsx'], states: ['first-week', 'middle', 'last-week'], keys: ['label.week', 'label.weekOfCount'] },
  { id: 'plan.session-cards', title: 'Session cards', what: 'One card per session, with its exercises and rest.', screen: 'plan', components: ['src/ui/views/PlanView.tsx'], states: ['past', 'next', 'future'], keys: ['status.nextSession'] },
  { id: 'plan.deep-link', title: 'Deep link to a session', what: 'The control that opens a session from a plan card.', screen: 'plan', components: ['src/ui/views/PlanView.tsx'], states: ['enabled', 'no-plan'], keys: [] },

  // --- targets, seven figures ---
  { id: 'targets.energy', title: 'Energy target', what: 'The daily energy figure and its unit.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['default'], keys: [] },
  { id: 'targets.protein', title: 'Protein target', what: 'The daily protein figure and its unit.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['default'], keys: [] },
  { id: 'targets.fluid', title: 'Fluid target', what: 'The daily beverage intake target.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['default'], keys: [] },
  { id: 'targets.expected-rate', title: 'Expected rate', what: 'The expected rate of body mass change.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['default', 'maintenance'], keys: [] },
  { id: 'targets.creatine-dose', title: 'Creatine dose', what: 'The daily dose and the sentence that defines it.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['default'], keys: [] },
  { id: 'targets.why', title: 'The why disclosure', what: 'RMR and TDEE behind the "why?" summary, under contract R9.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['closed', 'open'], keys: ['label.rmr', 'label.tdee', 'why.beverageDefault'] },
  { id: 'targets.intake-check-in', title: 'Intake check-in', what: 'The daily energy and beverage entry, and its progress lines.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['empty', 'partial', 'met', 'error'], keys: ['advice.intakeRejected', 'button.recordIntake', 'hero.intakeCheckIn', 'label.energyProgress', 'label.proteinProgress', 'quantity.energyIntake', 'quantity.proteinIntake'] },
  { id: 'targets.empty', title: 'Targets empty state', what: 'What Targets says before a profile exists.', screen: 'targets', components: ['src/ui/views/TargetsView.tsx'], states: ['no-profile'], keys: ['advice.noProfileSetupFirst'] },

  // --- log ---
  { id: 'log.body-mass-chart', title: 'Body mass chart', what: 'The body mass series and its axes.', screen: 'log', components: ['src/ui/components/BodyMassChart.tsx', 'src/ui/views/LogView.tsx'], states: ['empty', 'plotted'], keys: ['advice.noBodyMassLogged', 'hero.bodyMass'] },
  { id: 'log.compliance-grid', title: 'Compliance grid', what: 'The grid of sessions met and missed by week.', screen: 'log', components: ['src/ui/components/ComplianceGrid.tsx'], states: ['empty', 'plotted'], keys: ['advice.noWeeksYet', 'hero.compliance', 'label.complianceGrid', 'status.complianceWeek', 'status.markCompleted', 'status.markMissed', 'status.markNotPlanned', 'status.markPlanned', 'status.markSkipped'] },
  { id: 'log.amrap-spark', title: 'AMRAP spark', what: 'The reps-per-week spark line.', screen: 'log', components: ['src/ui/components/AmrapSpark.tsx'], states: ['empty', 'plotted'], keys: ['hero.repsPerWeek', 'status.amrapBest'] },
  { id: 'log.records', title: 'Personal records', what: 'The record list and what counts as a record.', screen: 'log', components: ['src/ui/components/PRList.tsx'], states: ['empty', 'listed'], keys: ['advice.noSetsLogged', 'hero.personalRecords', 'status.estimated1RM', 'status.noEstimated1RM'] },
  { id: 'log.empty', title: 'Log empty state', what: 'What Log says before anything has been logged.', screen: 'log', components: ['src/ui/views/LogView.tsx'], states: ['no-profile', 'no-data'], keys: [] },

  // --- atlas, three rarities ---
  { id: 'atlas.count', title: 'Collected count', what: 'The count line above the grid.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['none', 'partial', 'complete'], keys: ['advice.atlas', 'hero.atlas', 'label.atlasCollected'] },
  { id: 'atlas.rarity.common', title: 'Common section', what: 'The common rarity heading, count and grid.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['default'], keys: ['label.rarityCommon'] },
  { id: 'atlas.rarity.uncommon', title: 'Uncommon section', what: 'The uncommon rarity heading, count and grid.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['default'], keys: ['label.rarityUncommon'] },
  { id: 'atlas.rarity.rare', title: 'Rare section', what: 'The rare rarity heading, count and grid.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['default'], keys: ['label.rarityRare'] },
  { id: 'atlas.locked-slot', title: 'Locked slot', what: 'An undiscovered card, and the name a screen reader hears.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['locked'], keys: ['status.undiscovered'] },
  // 'button.closeModal' moved to setup.body with Brief B: the body step's two new popups render
  // it too, and setup now comes first in screen order, so it wins the claim per "the first screen
  // in app order that renders it" rather than being catalogued twice.
  { id: 'atlas.detail-dialog', title: 'Card dialog', what: 'The card body, its citation and the close control.', screen: 'atlas', components: ['src/ui/views/AtlasView.tsx'], states: ['open'], keys: ['label.atlasSource'] },

  // --- settings, the SETTINGS_ROWS ids in order ---
  { id: 'settings.profile', title: 'Profile fields', what: 'The active profile, the display unit and the editable profile values.', screen: 'settings', components: ['src/ui/views/SettingsView.tsx'], states: ['default', 'invalid'], keys: ['advice.storedUnitsUnchanged', 'error.outsideAccepted', 'hero.profile', 'label.activeProfile', 'label.displayUnit'] },
  { id: 'settings.equipment-steps', title: 'Equipment steps', what: 'The load increments the suggested load is rounded to.', screen: 'settings', components: ['src/ui/views/SettingsView.tsx'], states: ['default'], keys: ['hero.equipmentSteps'] },
  { id: 'settings.hydration', title: 'Hydration row', what: 'The daily beverage target and the default it starts from.', screen: 'settings', components: ['src/ui/views/SettingsView.tsx'], states: ['default'], keys: ['advice.beverageDefault', 'hero.hydration', 'quantity.dailyBeverageTarget'] },
  { id: 'settings.reminders', title: 'Reminders panel', what: 'The push state line and the enable control.', screen: 'settings', components: ['src/ui/components/ReminderSettingsPanel.tsx'], states: ['not-configured', 'unsupported', 'needs-install', 'denied', 'off', 'needs-reenable', 'active'], keys: ['advice.reminderSubscribeFailed', 'advice.reminderSyncFailed', 'hero.reminders', 'label.remindersEnable', 'status.remindersActive', 'status.remindersDenied', 'status.remindersNeedInstall', 'status.remindersNeedReenable', 'status.remindersOff', 'status.remindersPending', 'status.remindersUnconfigured', 'status.remindersUnsupported'] },
  { id: 'settings.reminders.lead-times', title: 'Reminder lead times', what: 'The day-of time and the lead times before a session.', screen: 'settings', components: ['src/ui/components/ReminderSettingsPanel.tsx'], states: ['default'], keys: ['label.reminderDayOfTime', 'label.reminderLead', 'label.reminderLeadTimes'] },
  { id: 'settings.motivation-clip', title: 'Motivation clip', what: 'The clip picker, its size limit and the clear control.', screen: 'settings', components: ['src/ui/motivation/MotivationSettings.tsx', 'src/ui/settings/DataSection.tsx'], states: ['none', 'stored', 'too-large', 'clear-failed'], keys: ['advice.clipClearFailed', 'advice.motivationClipLimit', 'advice.motivationClipStorage', 'button.motivationClipPreview', 'button.motivationClipRemove', 'hero.motivationVideo', 'label.motivationClipChoose', 'label.motivationClipReplace', 'status.motivationClipNone', 'status.motivationClipNotStored', 'status.motivationClipNotVideo', 'status.motivationClipStored', 'status.motivationClipTooLarge'] },
  { id: 'settings.skin.picker', title: 'Skin picker', what: 'Clinical, Limelight and Board, and what a skin may change.', screen: 'settings', components: ['src/ui/settings/SkinSettings.tsx'], states: ['clinical', 'limelight', 'board'], keys: ['advice.skinChanges', 'hero.skin', 'label.settingsSkin', 'option.skinBoard', 'option.skinClinical', 'option.skinLimelight'] },
  { id: 'settings.skin.sounds', title: 'Sounds toggle', what: 'The switch for the app sounds.', screen: 'settings', components: ['src/ui/settings/SkinSettings.tsx'], states: ['on', 'off'], keys: ['label.settingsSounds', 'advice.soundsSilent'] },
  { id: 'settings.skin.hotkeys', title: 'Hotkeys toggle', what: 'The switch for the single-character shortcuts.', screen: 'settings', components: ['src/ui/settings/SkinSettings.tsx'], states: ['on', 'off'], keys: ['advice.hotkeysOff', 'label.settingsHotkeys', 'advice.hotkeysKeyboardOnly'] },
  { id: 'settings.data.export', title: 'Export', what: 'The JSON backup, the text summary and the calendar file.', screen: 'settings', components: ['src/ui/views/ExportView.tsx', 'src/domain/export/summary.ts'], states: ['ready', 'no-profile'], keys: ['advice.calendarAlarms', 'advice.exportUnavailable', 'advice.jsonIsBackup', 'advice.targetsNotEstimatedForProfile', 'button.downloadCalendar', 'button.downloadJson', 'button.downloadSummary', 'hero.exportImport', 'label.downloads'] },
  { id: 'settings.data.import', title: 'Import', what: 'The file picker, and what an invalid file does.', screen: 'settings', components: ['src/ui/views/ExportView.tsx'], states: ['idle', 'invalid', 'done'], keys: ['advice.fileUnreadable', 'advice.importInvalidNoChange', 'advice.importParseFailed', 'advice.importReplaces', 'button.checkImport', 'button.downloadBackup', 'button.replaceData', 'label.chooseExportFile', 'label.confirmReplace', 'label.importSection', 'label.pasteExport', 'status.importOk'] },
  // `advice.dataOnDevice` moved to shell.footer (P10 Brief D): DataSection.tsx still renders the
  // same sentence, but the footer now renders it first in app order, and the whole-tree claim
  // map files a shared key once, under the first screen that renders it.
  { id: 'settings.data.on-device', title: 'Data on device', what: 'The heading naming where the document is held; the sentence itself is filed under shell.footer.', screen: 'settings', components: ['src/ui/settings/DataSection.tsx'], states: ['default'], keys: ['hero.dataOnDevice'] },
  { id: 'settings.data.wipe', title: 'Wipe', what: 'The control that destroys the document, and its confirm.', screen: 'settings', components: ['src/ui/settings/DataSection.tsx'], states: ['idle', 'confirming'], keys: ['advice.wipeRemoves', 'button.wipeAll', 'button.wipeConfirm', 'label.confirmWipe'] },
  { id: 'settings.data.legacy-delete', title: 'Legacy delete', what: 'The old app keys, the download that must precede the delete.', screen: 'settings', components: ['src/ui/settings/DataSection.tsx'], states: ['absent', 'present', 'confirming'], keys: ['advice.deleteLegacy', 'advice.legacyOldDataKept', 'button.deleteLegacy', 'button.downloadLegacyJson', 'button.legacyDeleteOld', 'button.legacyReopen', 'label.confirmDeleteLegacy'] },

  // --- install ---
  { id: 'install.intro', title: 'Install guide heading', what: 'The heading and the sentence naming what only the installed app can do.', screen: 'install', components: ['src/ui/components/InstallGuide.tsx'], states: ['default'], keys: ['advice.installOnlyInstalledApp', 'hero.installHomeScreen'] },
  { id: 'install.ios', title: 'Install on iOS', what: 'The Safari, Share and Add to Home Screen steps.', screen: 'install', components: ['src/ui/components/InstallGuide.tsx'], states: ['default'], keys: ['advice.installIosVersion', 'label.installIos', 'status.installIosAdd', 'status.installIosOpen', 'status.installIosSafari', 'status.installIosShare'] },
  { id: 'install.android', title: 'Install on Android', what: 'The menu and Install app steps.', screen: 'install', components: ['src/ui/components/InstallGuide.tsx'], states: ['default'], keys: ['label.installAndroid', 'status.installAndroidInstall', 'status.installAndroidMenu', 'status.installAndroidOpen'] },

  // --- popups ---
  { id: 'popup.missed-week', title: 'Missed-week popup', what: 'The clip, the two sound lines and the single Dismiss control.', screen: 'popup', components: ['src/ui/motivation/MotivationModal.tsx', 'src/ui/motivation/MotivationGate.tsx', 'src/domain/motivation/trigger.ts'], states: ['muted', 'unmuted', 'no-clip'], keys: ['advice.motivationPreview', 'advice.tapForSound', 'advice.tapToMute', 'advice.weekMissed', 'advice.weekMissedNone', 'hero.motivationPreview'] },
  { id: 'popup.phase-transition', title: 'Phase transition', what: 'The block change cutscene.', screen: 'popup', components: ['src/ui/components/PhaseTransition.tsx'], states: ['entering', 'shown'] },
  { id: 'popup.spotlight', title: 'Spotlight palette', what: 'The command palette, its filter and its results.', screen: 'popup', components: ['src/ui/components/Spotlight.tsx'], states: ['open', 'no-results'] },
  { id: 'popup.konami', title: 'Konami overlay', what: 'The overlay the sequence raises, and the way out.', screen: 'popup', components: ['src/ui/components/KonamiOverlay.tsx'], states: ['open'] },
  { id: 'popup.capsule-write', title: 'Capsule write', what: 'The note field, the open date and the seal control.', screen: 'popup', components: ['src/ui/components/TimeCapsule.tsx'], states: ['empty', 'too-short', 'too-long', 'date-out-of-range'], keys: ['advice.capsuleDateRange', 'advice.capsuleDefaultMoved', 'advice.capsuleNoteLong', 'advice.capsuleNoteShort', 'button.sealCapsule', 'label.capsuleNote', 'label.capsuleOpensOn'] },
  { id: 'popup.capsule-read', title: 'Capsule read', what: 'The note as it reads on the open date.', screen: 'popup', components: ['src/ui/components/TimeCapsule.tsx'], states: ['sealed', 'openable', 'opened'], keys: [] },
  { id: 'popup.confirm-destructive', title: 'Destructive confirm', what: 'The dialog that gates the wipe and the legacy delete.', screen: 'popup', components: ['src/ui/components/ConfirmDestructive.tsx'], states: ['download-pending', 'type-to-confirm', 'armed'] },
  { id: 'popup.modal-shell', title: 'Modal shell', what: 'The frame every dialog shares: focus trap, close, backdrop.', screen: 'popup', components: ['src/ui/components/ModalShell.tsx'], states: ['open'] },
  { id: 'popup.migration.explain', title: 'Migration, explain', what: 'What the old data is and what the import will do.', screen: 'popup', components: ['src/ui/migration/MigrationWizard.tsx', 'src/ui/migration/MigrationGate.tsx'], states: ['explain'], keys: ['advice.legacyFound', 'advice.legacyNothingDeleted', 'advice.legacyUnitRequired', 'button.legacyDismiss', 'button.legacyPreview', 'disclosure.legacyBodyMassEvidence', 'disclosure.legacyTransfers', 'disclosure.whatTransfers', 'hero.legacyImport', 'label.legacyBodyMassUnit', 'label.legacyLoadUnit', 'label.legacyMassUnitKg', 'label.legacyMassUnitLb', 'label.legacyUnitKg', 'label.legacyUnitLb'] },
  { id: 'popup.migration.preview', title: 'Migration, preview', what: 'What the import found, before anything is written.', screen: 'popup', components: ['src/ui/migration/MigrationWizard.tsx'], states: ['preview', 'refused'], keys: ['advice.legacyApplyFailed', 'advice.legacyRefused', 'button.legacyApply', 'disclosure.whatWasNotMatched', 'disclosure.whatWasRefused', 'hero.legacyPreview'] },
  { id: 'popup.migration.applied', title: 'Migration, applied', what: 'What was written, and what happens to the old keys.', screen: 'popup', components: ['src/ui/migration/MigrationWizard.tsx'], states: ['applied'], keys: ['advice.legacyOldDataDeleted', 'advice.legacyStoreUnconfirmed', 'advice.legacyStored', 'button.legacyClose', 'button.legacyKeepOld', 'hero.legacyDone'] },
  { id: 'popup.form-cues', title: 'Form cues', what: 'The technique reference for one exercise.', screen: 'popup', components: ['src/ui/components/FormCuesModal.tsx'], states: ['open'] },
  { id: 'popup.video', title: 'Video modal', what: 'The clip player and its close control.', screen: 'popup', components: ['src/ui/components/VideoModal.tsx'], states: ['open', 'failed'], keys: ['advice.noClipRecorded', 'button.nextInstance', 'button.openClip', 'button.searchInstance', 'label.formReference', 'label.videoSearch', 'status.videoInstance'] },

  // --- toasts, the five ToastKind members ---
  { id: 'toast.undo', title: 'Undo toast', what: 'The toast that offers to undo a delete, with its deadline.', screen: 'toast', components: ['src/ui/components/ToastQueue.tsx'], states: ['live', 'expired'], keys: ['button.undo'] },
  { id: 'toast.milestone', title: 'Milestone toast', what: 'The set-count milestone line.', screen: 'toast', components: ['src/ui/components/ToastQueue.tsx'], states: ['shown'], keys: ['status.milestoneSets'] },
  { id: 'toast.coach', title: 'Coach toast', what: 'The progression line after a logged set.', screen: 'toast', components: ['src/ui/components/ToastQueue.tsx', 'src/domain/training/coach.ts'], states: ['shown'], keys: ['coach.aboveRange', 'coach.aboveRangeOne', 'coach.belowRange', 'coach.durationLogged', 'coach.insideRange', 'coach.loadPr', 'coach.overSuggested', 'coach.repPr', 'coach.setLogged', 'coach.setReadout', 'coach.topOfRange', 'coach.underSuggested', 'label.coachNote'] },
  { id: 'toast.telemetry', title: 'Telemetry toast', what: 'The line reporting a background action.', screen: 'toast', components: ['src/ui/components/ToastQueue.tsx'], states: ['shown'], keys: ['label.telemetry'] },
  { id: 'toast.specimen', title: 'Specimen toast', what: 'The card-drawn line that points at Atlas.', screen: 'toast', components: ['src/ui/components/ToastQueue.tsx'], states: ['shown'], keys: ['status.specimenAcquired'] },
];

/**
 * Keys the table holds and no screen renders, each with the file and line that proves it, so the
 * coverage gate can tell "excused" from "forgotten". A key here can never be claimed by a part and
 * a key claimed by a part can never be here. Step 3 fills this from the --unplaced list.
 */
/** @type {Record<string, string>} */
export const NOT_RENDERED = {
  'advice.noCardsMatch': 'src/ui/views/AtlasView.tsx:28 says the key goes unrendered',
  'hero.weekReview': 'src/skins/limelight/Icon.tsx:99 lists it as one of the two keys without a call site; the week-review screen is not built',
  'status.prStamp': 'src/skins/limelight/Icon.tsx:99 lists it as one of the two keys without a call site; src/ui/components/WeekStamp.tsx:33 says the stamp now reads status.weekMetStamp',
};
