// scripts/alpha-walk.mjs
//
// The guided alpha walkthrough: the tester's path through the app, as data. P10 Task 17.
//
// WHY THIS FILE EXISTS. The eight pages under docs/feedback/pages/ are grouped by code
// structure, so one page holds every popup in the app and another holds every toast. The owner
// asked for the opposite: "it would be much easier for me to give the feedback 'as i go through
// the app' ... so it would be better if it was a guided alpha test." Decision
// `alpha-guided-walkthrough` records that. This table is the walk; scripts/alpha-walk-pages.mjs
// renders it.
//
// WHAT A STEP IS. One thing the tester can see at once, with the action that reaches it. A popup,
// a toast or a sub-state is a step of its own placed immediately after the step that triggers it,
// never a page of its own at the far end of the app.
//
// THE THREE FIELDS THAT ARE NOT PROSE.
//   `keys`  the copy keys on that step, in the order the app paints them top to bottom. Every key
//           in docs/feedback/catalogue.json appears in exactly ONE step, the first place the
//           tester meets it, so a shared control (button.cancel, disclosure.why, button.dismiss,
//           button.closeModal) is reviewed once and never again.
//   `parts` the catalogue part ids the step covers. Part ids are the ledger key for every comment
//           and are unchanged by this reorganisation, so a comment written here reaches the same
//           task a comment written on the old pages would have. A part may be covered by more
//           than one step; a key may not.
//   `only`  the condition a step needs. A step with `only` is skippable, and the page says so.
//
// This module writes nothing and reads nothing. It is data, imported by the generator and by the
// generator's --check.

/**
 * The seven stages, in the order a first-time user meets the app.
 *
 * `file` and `id` are stable: `id` keys docs/feedback/walk/urls.json and the pager, and `file` is
 * the path the Artifact tool redeploys to.
 */
export const STAGES = [
  {
    n: 0,
    id: 'w0-how-to-test',
    file: 'w0-how-to-test.html',
    title: 'How To Run The Walkthrough',
    short: 'How to test',
    steps: [],
  },

  {
    n: 1,
    id: 'w1-first-open',
    file: 'w1-first-open.html',
    title: 'First Open And Setup',
    short: 'First open and setup',
    steps: [
      {
        id: 'w1.01',
        title: 'The intro sequence',
        do: 'Open the app for the very first time. Tap anywhere, or press any key, to move past the first four slides.',
        see: 'A caveat slide types itself out, with a small ascii figure and "click to continue" at the foot. Each tap replaces it with the next.',
        keys: ['advice.clickToContinue'],
        parts: ['intro.sequence'],
      },
      {
        id: 'w1.02',
        title: 'Skipping the intro',
        do: 'Open the app again (or clear its storage) and tap "skip" on any slide.',
        see: 'The sequence ends immediately and the app behind it appears; it never runs again on this device.',
        keys: ['button.skipIntro'],
        parts: ['intro.skip'],
      },
      {
        id: 'w1.03',
        title: 'The boot sequence',
        do: 'Open the app from its Home Screen icon and watch without touching the screen.',
        see: 'Dotted lines print one after another until the last one lands.',
        keys: [
          'hero.boot',
          'status.bootConsole',
          'status.bootOk',
          'status.bootPlan',
          'status.bootPlanName',
          'status.bootWeek',
          'status.bootSchedule',
          'status.bootStore',
          'status.bootReady',
        ],
        parts: ['boot.sequence'],
      },
      {
        id: 'w1.04',
        title: 'Skipping the boot',
        do: 'Open the app again and tap "skip it" while the lines are still printing.',
        see: 'The sequence stops and the app behind it appears.',
        keys: ['button.skipBoot'],
        parts: ['boot.skip'],
      },
      {
        id: 'w1.05',
        title: 'The top bar',
        do: 'Look at the strip across the top of the screen, while setup is still running.',
        see: 'Only the brand line. The moving instruction and the plan position wait for a profile to exist.',
        keys: [
          'advice.setupInstruction',
        ],
        parts: ['shell.topbar'],
      },
      {
        id: 'w1.06',
        title: 'The footer',
        do: 'Scroll to the very bottom of the screen, even while setup is still running.',
        see: 'The author, a link to the repository, the version and build, the last update, whether local data has finished loading, that everything stays on this device, the safety disclaimer from the intro, and the licence.',
        keys: [
          'footer.builtBy',
          'footer.repository',
          'footer.version',
          'footer.updated',
          'shell.status.loading',
          'shell.status.loaded',
          'advice.dataOnDevice',
          'footer.licence',
        ],
        parts: ['shell.footer'],
      },
      {
        id: 'w1.07',
        title: 'Setup, step 1: units',
        do: 'Read the heading and the line above the choice, then pick metric or imperial.',
        see: 'A heading naming the group this step belongs to, a step counter, a title, a lead-in line, two options, and a note under them.',
        keys: [
          'setup.hero',
          'group.settings',
          'group.personal',
          'group.goal',
          'step.units',
          'label.units',
          'advice.unitsOnce',
          'label.unitsMetric',
          'label.unitsImperial',
        ],
        parts: ['setup.progress', 'setup.units'],
      },
      {
        id: 'w1.08',
        title: 'The wizard controls',
        do: 'Look at the foot of the setup screen, then tap "go on".',
        see: 'Back appears from step 2 onward; the forward control sits beside it.',
        keys: ['button.back', 'button.continue'],
        parts: ['setup.nav'],
      },
      {
        id: 'w1.09',
        title: 'Setup, step 2: time zone',
        do: 'Read the note, then check the zone the app has filled in.',
        see: 'One note, one field, and an error line if the zone is not a real one.',
        keys: [
          'step.timezone',
          'advice.timezoneDetected',
          'advice.timezonePick',
          'label.timezone',
          'advice.timezoneInvalid',
        ],
        parts: ['setup.timezone'],
      },
      {
        id: 'w1.10',
        title: 'Setup, step 3: name, age, sex, height, mass',
        do: 'Fill the fields from the top of the screen down to body mass. Leave one blank and tap "go on" to see the errors. Then open the sex explainer.',
        see: 'A name field, then age and a sex choice with a link under it, then height and body mass.',
        keys: [
          'step.body',
          'label.name',
          'quantity.age',
          'label.sex',
          'label.sexMale',
          'label.sexFemale',
          'advice.sexWorkaround',
          'label.sexRationale',
          'quantity.bodyMass',
          'quantity.height',
          'label.metres',
          'label.centimetres',
          'label.feet',
          'label.inches',
          'error.valueRequired',
          'error.wholeNumber',
          'error.positive',
        ],
        parts: ['setup.body'],
      },
      {
        id: 'w1.11',
        title: 'Setup, step 3: body fat',
        do: 'Scroll down the same screen. Percentage is pre-selected; open the estimate-chart link, then pick the tape option and open "why?".',
        see: 'Three options with percentage first, an estimate link above the percentage box, the tape fields under the second, and the note and why disclosure at the foot.',
        keys: [
          'label.bodyFatKnown',
          'label.bodyFatTape',
          'label.bodyFatNone',
          'advice.estimateBodyFat',
          'label.bodyFatChart',
          'quantity.bodyFat',
          'advice.tapeMethod',
          'quantity.neck',
          'quantity.abdomenI',
          'quantity.abdomenII',
          'quantity.hip',
          'disclosure.why',
          'advice.tapeNeedMale',
          'advice.tapeNeedFemale',
          'advice.tapeOutOfDomain',
          'advice.bodyFatEstimate',
          'why.bodyFatEstimate',
          'advice.bodyFatOptional',
          'why.bodyFatOptional',
        ],
        parts: ['setup.body'],
      },
      {
        id: 'w1.12',
        title: 'Setup, step 4: equipment & availability',
        do: 'Move each of the three sliders through every position, opening the Examples ' +
          'disclosure on the first two. Then move the Equipment Access slider through Full ' +
          'gym, Home gym and Body weight only in turn to see the load increments box and each ' +
          'equipment question it reveals.',
        see: 'Three sliders, each naming its current position in text and (for the first two) ' +
          'an Examples disclosure; a bordered box with the three load increments; then, ' +
          'depending on the Equipment Access position, a walk-to-the-gym question or an ' +
          'equipment multi-select.',
        keys: [
          'step.training',
          'label.activity',
          'option.activitySedentary',
          'option.activityModerate',
          'option.activityVigorous',
          'disclosure.examples',
          'label.experience',
          'option.experienceNovice',
          'option.experienceIntermediate',
          'option.experienceAdvanced',
          'label.equipmentAccess',
          'option.accessBodyweight',
          'option.accessHomeAndBodyweight',
          'option.accessHome',
          'option.accessFullAndHome',
          'option.accessFullGym',
          'advice.loadSteps',
          'quantity.barbellStep',
          'quantity.dumbbellStep',
          'quantity.stackStep',
          'advice.walkToGym',
          'button.yes',
          'button.no',
          'quantity.walkMinutes',
          'advice.equipmentInventoryPrompt',
          'label.homeEquipmentAerobic',
          'option.homeTreadmill',
          'option.homeElliptical',
          'option.homeRowingMachine',
          'label.homeEquipmentDumbbells',
          'label.homeEquipmentMachines',
          'option.homeSquatRack',
          'option.homeCableMachine',
          'option.homeBench',
          'option.homeLegPress',
          'option.homeLatPulldown',
          'option.homeSmithMachine',
          'option.bodyweightYogaMat',
          'option.bodyweightSkippingRope',
          'option.bodyweightPullUpBar',
          'option.bodyweightResistanceBands',
        ],
        parts: ['setup.training'],
      },
      {
        id: 'w1.13',
        title: 'Setup, step 5: goal',
        do: 'Pick a goal, then read down to the two checkboxes.',
        see: 'A goal menu, a target mass, a target date, and two options with a note under each.',
        keys: [
          'step.goal',
          'label.goal',
          'option.goalFatLoss',
          'option.goalMuscleGain',
          'option.goalRecomposition',
          'option.goalMaintenance',
          'quantity.targetBodyMass',
          'label.targetDate',
          'label.creatine',
          'advice.creatineOnly',
          'label.weighIn',
          'advice.weighIn',
        ],
        parts: ['setup.goal'],
      },
      {
        id: 'w1.14',
        title: 'Setup, step 6: availability',
        do: 'Pick your training days and set a start time and a length for one of them. Then clear every day to see the error.',
        see: 'A sessions-per-week field, then seven weekday rows, each with a time and a length.',
        keys: [
          'step.availability',
          'label.sessionsPerWeek',
          'weekday.monday',
          'weekday.tuesday',
          'weekday.wednesday',
          'weekday.thursday',
          'weekday.friday',
          'weekday.saturday',
          'weekday.sunday',
          'label.startTime',
          'label.duration',
          'quantity.weeklySessionTarget',
          'error.pickOneDay',
        ],
        parts: ['setup.availability'],
      },
      {
        id: 'w1.15',
        title: 'Setup, step 7: programme length',
        do: 'Set how many weeks the plan runs for.',
        see: 'One field, a note about deload weeks, and a cardio checkbox.',
        keys: [
          'step.programme',
          'quantity.programmeWeeks',
          'advice.deloadEveryFourth',
          'label.includeCardio',
        ],
        parts: ['setup.programme'],
      },
      {
        id: 'w1.16',
        title: 'Setup, step 8: guidance',
        do: 'Read the supplement and kit guidance, then tap Continue.',
        see: 'Sections on creatine, caffeine, protein powder, and basic kit, with personalized doses.',
        keys: ['step.guidance', 'hero.guidance'],
        parts: ['setup.guidance'],
      },
      {
        id: 'w1.17',
        title: 'Setup, step 9: review',
        do: 'Read the two panels, then tap "lock it in".',
        see: 'The daily targets, then the programme summary, then the control that writes the profile.',
        keys: [
          'step.review',
          'hero.dailyTargets',
          'status.targetsNotEstimated',
          'label.energy',
          'label.protein',
          'label.fluid',
          'label.expectedRate',
          'status.rateUnknown',
          'label.creatineDose',
          'label.none',
          'hero.programme',
          'label.inTargetRange',
          'label.maintenanceOnly',
          'button.confirmStart',
        
          'hero.yourAnswers',
        ],
        parts: ['setup.review'],
      },
    ],
  },

  {
    n: 2,
    id: 'w2-today',
    file: 'w2-today.html',
    title: 'Today, First Look',
    short: 'Today',
    steps: [
      {
        id: 'w2.01',
        title: 'The top bar, now that a profile exists',
        do: 'On limelight or board, watch the top bar strip; switch tabs and look again. On clinical, read the still line at the same spot instead.',
        see: 'A moving strip carrying the instruction for the tab you are on and the session the cursor stands at, cycling on every screen except clinical, where one still line names the instruction alone.',
        keys: [
          'advice.todayInstruction',
          'advice.planInstruction',
          'advice.trainInstruction',
          'advice.targetsInstruction',
          'advice.logInstruction',
          'advice.atlasInstruction',
          'advice.settingsInstruction',
          'button.pauseUpdates',
          'label.planPosition',
          'status.sessionCursor',
          'status.planComplete',
          'hero.programmeComplete',
        ],
        parts: ['shell.topbar', 'shell.session-indicator'],
      },
      {
        id: 'w2.02',
        title: 'The tab strip',
        do: 'Look at the row of tabs, then tap each one and come back to "today".',
        see: 'Seven tabs and the palette control at the end of the row.',
        keys: [
          'nav.label',
          'nav.today',
          'nav.plan',
          'nav.train',
          'nav.targets',
          'nav.log',
          'nav.atlas',
          'nav.settings',
          'button.openSpotlight',
        ],
        parts: ['shell.tab-strip', 'shell.spotlight-button'],
      },
      {
        id: 'w2.03',
        title: 'The marquee',
        do: 'Watch the ticker at the top of today, then tap it to stop it.',
        see: 'A scrolling strip carrying this week against last week.',
        keys: [
          'button.pauseTicker',
          'status.weekDeltaPositive',
          'status.weekDeltaZero',
          'status.weekDeltaNegative',
        ],
        parts: ['today.marquee'],
      },
      {
        id: 'w2.04',
        title: 'The day, and the session card',
        do: 'Read the block under the marquee, from the small line at the top down through the exercise list.',
        see: 'An eyebrow, one headline for the day, and the exercises with their sets, reps and rest.',
        keys: [
          'hero.noPlan',
          'advice.completeSetup',
          'hero.sessionInProgress',
          'hero.sessionCompleted',
          'hero.sessionSkipped',
          'hero.noSessionToday',
          'advice.nextSession',
          'advice.noSessionIn14Days',
          'status.setsBy',
        ],
        parts: ['today.hero', 'today.session-card'],
      },
      {
        id: 'w2.05',
        title: 'The start control',
        do: 'Find the control under the session card. Do not press it yet.',
        see: 'One control that opens the session, or one that returns to a session already open.',
        keys: ['button.startSession', 'button.returnToSession'],
        parts: ['today.start'],
      },
      {
        id: 'w2.06',
        title: 'Mark the day done without training',
        do: 'Read "mark it done" beside the start control.',
        see: 'A control that closes today without opening the session.',
        keys: ['button.markCompleted'],
        parts: ['today.mark-completed'],
      },
      {
        id: 'w2.07',
        title: 'Skip today',
        do: 'Tap "not today satan", type a reason, then tap "never mind" to back out.',
        see: 'A reason field with a confirm and a cancel under it.',
        keys: [
          'button.skipToday',
          'label.skipReason',
          'button.confirmSkip',
          'button.cancel',
          'status.skipReason',
        ],
        parts: ['today.skip'],
      },
      {
        id: 'w2.08',
        title: 'Train something else',
        do: 'Tap "plot twist".',
        see: 'A short list of the labels this week still owes, one control each.',
        keys: ['button.trainSomethingElse', 'status.remainingThisWeek', 'button.trainLabelToday'],
        parts: ['today.label-picker'],
        only: 'only while the week still owes a label this day can take',
      },
      {
        id: 'w2.09',
        title: 'Pause the plan',
        do: 'Tap "on hiatus", read the day again, then tap "comeback tour".',
        see: 'The headline changes to a paused line, and the control becomes the one that lifts it.',
        keys: [
          'button.pausePlan',
          'status.planPaused',
          'advice.pauseHoldsCursor',
          'button.resumePlan',
        ],
        parts: ['today.pause'],
      },
      {
        id: 'w2.10',
        title: 'A refused control',
        do: 'Tap "on hiatus", then tap "LET\'S GO BABES" while the plan is paused.',
        see: 'A line above the day saying why the app refused, with a dismiss control.',
        keys: [
          'banner.actionRefused.tag',
          'button.dismiss',
          'status.refusalPaused',
          'status.refusalAlreadyStarted',
          'status.refusalSessionOpen',
          'status.refusalNotNextDay',
          'status.refusalLabelNotOffered',
          'status.refusalUnrecognised',
        ],
        parts: ['today.refusal-banner'],
      },
      {
        id: 'w2.11',
        title: 'The week stamp',
        do: 'Scroll below the controls at the end of a week that met its session target.',
        see: 'One stamp marking the week.',
        keys: ['status.weekMetStamp'],
        parts: ['today.week-stamp'],
        only: 'only after a week that met its target',
      },
      {
        id: 'w2.12',
        title: 'The missed-week panel',
        do: 'Scroll to the same place after a week that missed its target, once the popup has been dismissed.',
        see: 'A headline and a short paragraph about the week just gone.',
        keys: ['hero.weeklyTargetMissed', 'advice.interventionBody'],
        parts: ['today.intervention'],
        only: 'only after a missed week, and after the popup has been answered',
      },
      {
        id: 'w2.13',
        title: 'The time capsule',
        do: 'Keep scrolling to the capsule panel.',
        see: 'A heading, one line about what a capsule is, and one control.',
        keys: [
          'hero.timeCapsule',
          'advice.timeCapsule',
          'button.writeCapsule',
          'status.capsuleWritten',
          'advice.capsuleOpenDatePassed',
          'button.openCapsule',
          'button.readCapsule',
        ],
        parts: ['today.time-capsule'],
      },
      {
        id: 'w2.14',
        title: 'Write a capsule',
        do: 'Tap "write it", type two words, set an open date, then tap "seal it".',
        see: 'A dialog with a note field, an open date, and a seal control. Close is at its top right.',
        keys: [
          'label.capsuleNote',
          'advice.capsuleNoteShort',
          'advice.capsuleNoteLong',
          'label.capsuleOpensOn',
          'advice.capsuleDateRange',
          'advice.capsuleDefaultMoved',
          'status.capsuleSealed',
          'button.sealCapsule',
          'button.closeModal',
        ],
        parts: ['popup.capsule-write', 'popup.modal-shell'],
      },
      {
        id: 'w2.15',
        title: 'Read a capsule',
        do: 'Tap "read it" on a capsule whose open date has passed.',
        see: 'The note as you wrote it, on the date you chose.',
        keys: [],
        parts: ['popup.capsule-read'],
        only: 'only once a sealed capsule has reached its open date',
      },
      {
        id: 'w2.16',
        title: 'The fourteen-day strip',
        do: 'Scroll to the bottom of today and read the fourteen rows.',
        see: 'One row per day: weekday, date, time, label and a status glyph.',
        keys: [
          'hero.nextFourteenDays',
          'status.dayRest',
          'status.dayPlanned',
          'status.dayInProgress',
          'status.dayCompleted',
          'status.daySkipped',
          'status.dayPaused',
        ],
        parts: ['today.strip'],
      },
    ],
  },

  {
    n: 3,
    id: 'w3-session',
    file: 'w3-session.html',
    title: 'A Training Session',
    short: 'A session',
    steps: [
      {
        id: 'w3.01',
        title: 'Open the session',
        do: 'On today, tap "LET\'S GO BABES".',
        see: 'The session name with a small line above it, and a deload note when the block is a deload.',
        keys: [
          'status.sessionEyebrow',
          'advice.deloadBlock',
          'hero.train',
          'advice.noSessionToday',
          'advice.noProfileTrain',
        ],
        parts: ['train.header'],
      },
      {
        id: 'w3.02',
        title: 'The hydration banner',
        do: 'Read the band under the session name, then tap the drink control on it.',
        see: 'One cue about beverage intake, with either a log control or a why disclosure.',
        keys: [
          'advice.beverageShortfall',
          'advice.drinkToThirst',
          'button.logVolume',
          'advice.logPostSessionMass',
          'why.postSessionMass',
        ],
        parts: ['train.hydration-banner'],
      },
      {
        id: 'w3.03',
        title: 'The first exercise card',
        do: 'Tap the first exercise to open it, then read down the open card.',
        see: 'Last session, a suggested load with the reason beside it, the why disclosure, and two reference controls.',
        keys: [
          'status.lastSessionSets',
          'label.noSuggestedLoad',
          'label.suggestedLoad',
          'status.adviceAddLoad',
          'status.adviceExtendReps',
          'status.adviceHold',
          'status.adviceDeload',
          'button.formReference',
          'button.formCues',
          'button.addSet',
        ],
        parts: ['train.exercise-card'],
      },
      {
        id: 'w3.04',
        title: 'Form cues',
        do: 'On the first exercise card tap "Form cues".',
        see: 'A dialog holding the technique reference for that one exercise.',
        keys: [
          'label.formCues',
          'advice.noFormCues',
          'label.caution',
          'label.cueSetup',
          'label.cueExecution',
          'label.cueMistakes',
          'label.cueTip',
        ],
        parts: ['popup.form-cues'],
      },
      {
        id: 'w3.05',
        title: 'The form reference clip',
        do: 'Close Form cues, then tap "Form reference" on the same card.',
        see: 'A player, or a search panel when no clip is recorded for that exercise.',
        keys: [
          'label.formReference',
          'status.videoInstance',
          'button.nextInstance',
          'label.videoSearch',
          'advice.noClipRecorded',
          'button.openClip',
          'button.searchInstance',
        ],
        parts: ['popup.video'],
      },
      {
        id: 'w3.06',
        title: 'A set row',
        do: 'Close the clip. Read the first set row on the open card.',
        see: 'A set marker, a load field, a reps field, a log control and a delete.',
        keys: [
          'status.setCounter',
          'label.bonusSet',
          'button.deleteSet',
          'advice.durationNeeded',
          'button.logSet',
        ],
        parts: ['train.set-row'],
      },
      {
        id: 'w3.07',
        title: 'The coach toast',
        do: 'Type a load and reps into the first set row and tap "log it".',
        see: 'A toast at the foot of the screen reading what the set means for the next one.',
        keys: [
          'label.coachNote',
          'coach.loadPr',
          'coach.repPr',
          'coach.overSuggested',
          'coach.underSuggested',
          'coach.aboveRangeOne',
          'coach.aboveRange',
          'coach.belowRange',
          'coach.topOfRange',
          'coach.insideRange',
          'coach.setReadout',
        ],
        parts: ['toast.coach'],
      },
      {
        id: 'w3.08',
        title: 'The plain readout toast',
        do: 'Log a set on a timed hold, or on an exercise with no rep range.',
        see: 'The same toast, tagged as a readout rather than as a coach note.',
        keys: ['label.telemetry', 'coach.setLogged', 'coach.durationLogged'],
        parts: ['toast.telemetry', 'toast.coach'],
      },
      {
        id: 'w3.09',
        title: 'The rest panel',
        do: 'After logging a set, look above the exercise cards. Tap "+30 s", then tap "i\'m ready".',
        see: 'A countdown ring with the time left, a label, and two controls.',
        keys: [
          'status.restRemaining',
          'status.rest',
          'button.extendRest',
          'button.skipRest',
          'notification.restOver',
        ],
        parts: ['train.rest-panel'],
      },
      {
        id: 'w3.10',
        title: 'The undo toast',
        do: 'Tap "Delete" on the set you just logged.',
        see: 'A toast saying the set is gone, with an undo control and a deadline on it.',
        keys: ['coach.setDeleted', 'button.undo'],
        parts: ['toast.undo', 'train.set-row'],
      },
      {
        id: 'w3.11',
        title: 'The milestone toast',
        do: 'Keep logging sets until the running count crosses a milestone.',
        see: 'A toast naming the number of sets logged.',
        keys: ['status.milestoneSets'],
        parts: ['toast.milestone'],
        only: 'only when the set count crosses a milestone',
      },
      {
        id: 'w3.12',
        title: 'The specimen toast',
        do: 'Keep training. A card is drawn on its own schedule.',
        see: 'A toast saying a card was drawn, pointing at "the collection".',
        keys: ['status.specimenAcquired'],
        parts: ['toast.specimen'],
        only: 'only when a card is drawn',
      },
      {
        id: 'w3.13',
        title: 'Add an exercise the plan does not carry',
        do: 'Scroll past the last card and tap "Add exercise". Type a name, pick a kind, then tap "Add".',
        see: 'A name field with a character count, a kind menu, and a save control.',
        keys: [
          'button.addExercise',
          'quantity.exerciseName',
          'unit.characters',
          // Renamed here from setup.training, whose Equipment `<select>` Brief F replaced with
          // the Equipment Access slider (label.equipmentAccess): this is now the only place
          // 'label.equipment' renders, the "kind" select's own label.
          'label.equipment',
          'label.modality.barbell',
          'label.modality.dumbbell',
          'label.modality.machine',
          'label.modality.cable',
          'label.modality.bodyweight',
          'status.customExerciseRefused',
          'button.saveExercise',
        ],
        parts: ['train.add-custom-exercise'],
      },
      {
        id: 'w3.14',
        title: 'Body mass, before and after',
        do: 'Enter a body mass at the foot of the session, then enter one again after you finish.',
        see: 'One field before the session and one after, with a note when the drop is large.',
        keys: [
          'quantity.preSessionBodyMass',
          'button.logBodyMass',
          'quantity.postSessionBodyMass',
          'advice.fluidLoss',
          'why.fluidLoss',
        ],
        parts: ['train.body-mass-quick-log'],
      },
      {
        id: 'w3.15',
        title: 'Finish the session',
        do: 'Tap "that\'s a wrap", then tap "Back to Today".',
        see: 'The session closes and the control changes to the one that returns to today.',
        keys: ['button.finishSession', 'button.backToToday'],
        parts: ['train.completion'],
      },
    ],
  },

  {
    n: 4,
    id: 'w4-after',
    file: 'w4-after.html',
    title: 'After The Session',
    short: 'After the session',
    steps: [
      {
        id: 'w4.01',
        title: 'The run: the block strip',
        do: 'Tap "the run". Read the row of blocks at the top.',
        see: 'One card per block, with its session range and a deload flag on the deload blocks.',
        keys: [
          'label.blockStrip',
          'label.block',
          'status.blockSessions',
          'status.deloadTag',
          'status.deloadNote',
          'why.deloadSets',
        ],
        parts: ['plan.block-strip'],
      },
      {
        id: 'w4.02',
        title: 'The run: the week scrubber',
        do: 'Move the week control one week forward and one back.',
        see: 'A label and the week you are on out of the total.',
        keys: ['label.week', 'label.weekOfCount'],
        parts: ['plan.week-scrubber'],
      },
      {
        id: 'w4.03',
        title: 'The run: the session cards',
        do: 'Scroll the cards for the week on screen, then tap the one marked as next.',
        see: 'One card per session, with its exercises and rest, and a mark on the next one.',
        keys: ['status.nextSession'],
        parts: ['plan.session-cards', 'plan.deep-link'],
      },
      {
        id: 'w4.04',
        title: 'The numbers: the daily targets',
        do: 'Tap "the numbers". Read the five figures at the top.',
        see: 'Energy, protein, fluid, expected rate and creatine, each with its unit.',
        keys: [],
        parts: [
          'targets.energy',
          'targets.protein',
          'targets.fluid',
          'targets.expected-rate',
          'targets.creatine-dose',
        ],
      },
      {
        id: 'w4.05',
        title: 'The numbers: how they were worked out',
        do: 'Open "why?" under the figures.',
        see: 'Resting and total daily energy, and the basis for the beverage target.',
        keys: ['label.rmr', 'label.tdee', 'why.beverageDefault'],
        parts: ['targets.why'],
      },
      {
        id: 'w4.06',
        title: 'The numbers: the daily check-in',
        do: 'Enter an energy and a protein figure, then tap "Record intake".',
        see: 'Two fields, a record control, and two progress lines under them.',
        keys: [
          'hero.intakeCheckIn',
          'quantity.energyIntake',
          'quantity.proteinIntake',
          'advice.intakeRejected',
          'button.recordIntake',
          'label.energyProgress',
          'label.proteinProgress',
        ],
        parts: ['targets.intake-check-in'],
      },
      {
        id: 'w4.07',
        title: 'The numbers, before a profile exists',
        do: 'Read the string below. It is what "the numbers" says when setup has not run.',
        see: 'One line pointing back at setup.',
        keys: ['advice.noProfileSetupFirst'],
        parts: ['targets.empty'],
        only: 'only before setup is finished, so read it here rather than reaching it',
      },
      {
        id: 'w4.08',
        title: 'The archive: body mass',
        do: 'Tap "the archive". Read the first chart and open the "why?" under it.',
        see: 'A body mass series over time, or one line saying nothing is logged.',
        keys: ['hero.bodyMass', 'advice.noBodyMassLogged'],
        parts: ['log.body-mass-chart'],
      },
      {
        id: 'w4.09',
        title: 'The archive: the compliance grid',
        do: 'Scroll to the grid and read one row.',
        see: 'One row per week, one mark per planned session.',
        keys: [
          'hero.compliance',
          'label.complianceGrid',
          'status.complianceWeek',
          'status.markPlanned',
          'status.markCompleted',
          'status.markSkipped',
          'status.markMissed',
          'status.markNotPlanned',
          'advice.noWeeksYet',
        ],
        parts: ['log.compliance-grid'],
      },
      {
        id: 'w4.10',
        title: 'The archive: reps per week',
        do: 'Scroll to the spark lines.',
        see: 'One small line per exercise, with its best week under it.',
        keys: ['hero.repsPerWeek', 'status.amrapBest'],
        parts: ['log.amrap-spark'],
      },
      {
        id: 'w4.11',
        title: 'The archive: personal records',
        do: 'Scroll to the bottom of "the archive".',
        see: 'A list of records, each with an estimated one-rep maximum where one can be computed.',
        keys: [
          'hero.personalRecords',
          'status.estimated1RM',
          'status.noEstimated1RM',
          'advice.noSetsLogged',
        ],
        parts: ['log.records'],
      },
      {
        id: 'w4.12',
        title: 'The archive, before anything is logged',
        do: 'Read the empty state. It is what the screen shows before a set exists.',
        see: 'The headings with nothing under them.',
        keys: [],
        parts: ['log.empty'],
        only: 'only before any set or body mass is logged',
      },
      {
        id: 'w4.13',
        title: 'The collection: the count',
        do: 'Tap "the collection". Read the top of the screen.',
        see: 'A heading, one line about the cards, and how many you hold.',
        keys: ['hero.atlas', 'advice.atlas', 'label.atlasCollected'],
        parts: ['atlas.count'],
      },
      {
        id: 'w4.14',
        title: 'The collection: the three rarity sections',
        do: 'Scroll the three sections.',
        see: 'A heading and a count above each grid.',
        keys: ['label.rarityCommon', 'label.rarityUncommon', 'label.rarityRare'],
        parts: ['atlas.rarity.common', 'atlas.rarity.uncommon', 'atlas.rarity.rare'],
      },
      {
        id: 'w4.15',
        title: 'The collection: a locked slot',
        do: 'Look at a slot you have not filled.',
        see: 'A slot naming its rarity and nothing else about the card.',
        keys: ['status.undiscovered'],
        parts: ['atlas.locked-slot'],
      },
      {
        id: 'w4.16',
        title: 'The collection: a card',
        do: 'Tap a card you hold.',
        see: 'The card body and the source it is drawn from.',
        keys: ['label.atlasSource'],
        parts: ['atlas.detail-dialog'],
        only: 'only once you hold at least one card',
      },
    ],
  },

  {
    n: 5,
    id: 'w5-settings',
    file: 'w5-settings.html',
    title: 'Settings And Data',
    short: 'Settings and data',
    steps: [
      {
        id: 'w5.01',
        title: 'The profile fields',
        do: 'Tap "backstage". Read the first block, then change the display unit.',
        see: 'The profile in use, the display unit, and the fields you set during setup.',
        keys: [
          'hero.profile',
          'label.activeProfile',
          'label.displayUnit',
          'advice.storedUnitsUnchanged',
          'error.outsideAccepted',
        ],
        parts: ['settings.profile'],
      },
      {
        id: 'w5.02',
        title: 'The equipment steps',
        do: 'Scroll to the load increments.',
        see: 'The steps the suggested load is rounded to.',
        keys: ['hero.equipmentSteps'],
        parts: ['settings.equipment-steps'],
      },
      {
        id: 'w5.03',
        title: 'The beverage target',
        do: 'Scroll to the hydration block and open the "why?" under it.',
        see: 'A daily target, and the default it started from.',
        keys: ['hero.hydration', 'quantity.dailyBeverageTarget', 'advice.beverageDefault'],
        parts: ['settings.hydration'],
      },

      {
        id: 'w5.04',
        title: 'Reminders',
        do: 'Scroll to the reminders block and read the state line, then turn "Enable reminders" on.',
        see: 'A heading, one line saying what push is doing, and a switch.',
        keys: ['hero.reminders', 'status.remindersUnconfigured', 'label.remindersEnable'],
        parts: ['settings.reminders'],
      },
      {
        id: 'w5.05',
        title: 'Reminder times',
        do: 'Set the day-of time, then tick one of the lead times.',
        see: 'One time field and a set of lead times before a session.',
        keys: ['label.reminderDayOfTime', 'label.reminderLeadTimes', 'label.reminderLead'],
        parts: ['settings.reminders.lead-times'],
      },
      {
        id: 'w5.06',
        title: 'The install guide',
        do: 'Open the site in a browser tab rather than the installed app, then open the reminders block.',
        see: 'The install steps for iOS and for Android, printed in the reminders block.',
        keys: [
          'hero.installHomeScreen',
          'advice.installOnlyInstalledApp',
          'label.installIos',
          'status.installIosSafari',
          'status.installIosShare',
          'status.installIosAdd',
          'status.installIosOpen',
          'advice.installIosVersion',
          'label.installAndroid',
          'status.installAndroidMenu',
          'status.installAndroidInstall',
          'status.installAndroidOpen',
        ],
        parts: ['install.intro', 'install.ios', 'install.android'],
        only: 'only when the reminders block says the app must be installed first',
      },
      {
        id: 'w5.07',
        title: 'The motivation clip',
        do: 'Scroll to the clip block, tap "Choose a clip", pick a short video, then tap "sneak peek".',
        see: 'A heading, whether a clip is stored, a picker, a size note and a remove control.',
        keys: [
          'hero.motivationVideo',
          'status.motivationClipNone',
          'status.motivationClipStored',
          'label.motivationClipChoose',
          'label.motivationClipReplace',
          'advice.motivationClipStorage',
          'advice.motivationClipLimit',
          'button.motivationClipPreview',
          'button.motivationClipRemove',
          'status.motivationClipNotVideo',
          'status.motivationClipTooLarge',
          'status.motivationClipNotStored',
          'advice.clipClearFailed',
        ],
        parts: ['settings.motivation-clip'],
      },
      {
        id: 'w5.08',
        title: 'The skin picker',
        do: 'Scroll to "the look". Read the note, then leave the choice on limelight.',
        see: 'A heading, one line saying what a skin may change, and three options.',
        keys: [
          'hero.skin',
          'advice.skinChanges',
          'label.settingsSkin',
          'option.skinClinical',
          'option.skinLimelight',
          'option.skinBoard',
        ],
        parts: ['settings.skin.picker'],
      },
      {
        id: 'w5.09',
        title: 'Sounds and shortcuts',
        do: 'Look at the two switches under the skin picker.',
        see: 'One switch for the sounds, one for the single-key shortcuts, and a note under the second.',
        keys: ['label.settingsSounds', 'label.settingsHotkeys', 'advice.hotkeysOff'],
        parts: ['settings.skin.sounds', 'settings.skin.hotkeys'],
      },
      {
        id: 'w5.10',
        title: 'Export',
        do: 'Scroll to the data block and tap "Download JSON".',
        see: 'Three downloads and a note under each about what the file is for.',
        keys: [
          'hero.exportImport',
          'label.downloads',
          'button.downloadJson',
          'button.downloadSummary',
          'button.downloadCalendar',
          'advice.jsonIsBackup',
          'advice.calendarAlarms',
          'advice.exportUnavailable',
          'advice.targetsNotEstimatedForProfile',
        ],
        parts: ['settings.data.export'],
      },
      {
        id: 'w5.11',
        title: 'Import',
        do: 'Choose the file you just downloaded, tap "Check import", then read the confirm before you tap "Replace data".',
        see: 'A paste field, a file picker, a check control, and a confirm before anything is written.',
        keys: [
          'label.importSection',
          'advice.importReplaces',
          'advice.importInvalidNoChange',
          'label.pasteExport',
          'label.chooseExportFile',
          'button.checkImport',
          'label.confirmReplace',
          'button.downloadBackup',
          'button.replaceData',
          'status.importOk',
          'advice.importParseFailed',
          'advice.fileUnreadable',
        ],
        parts: ['settings.data.import'],
      },
      {
        id: 'w5.12',
        title: 'Where the data lives',
        do: 'Read the block under the import section.',
        see: 'A heading naming where the document is held; the sentence itself is reviewed at the footer, step w1.06.',
        keys: ['hero.dataOnDevice'],
        parts: ['settings.data.on-device'],
      },
      {
        id: 'w5.13',
        title: 'Wipe',
        do: 'Tap "Wipe all data". Read what appears. Do not confirm unless you have a backup.',
        see: 'A note about what is removed, then a confirm gate.',
        keys: ['button.wipeAll', 'advice.wipeRemoves', 'label.confirmWipe', 'button.wipeConfirm'],
        parts: ['settings.data.wipe'],
      },
      {
        id: 'w5.14',
        title: 'The destructive confirm',
        do: 'With the wipe gate open, tap the download control inside it, then read the line above the confirm.',
        see: 'A line that changes once a copy has been taken, and a word you must type before the confirm arms.',
        keys: ['advice.exportBeforeConfirm', 'status.exportTaken'],
        parts: ['popup.confirm-destructive'],
      },
      {
        id: 'w5.15',
        title: 'Delete the old app data',
        do: 'Tap "Delete legacy data" at the bottom of the data block.',
        see: 'A note, the same confirm gate, and a download that must precede the delete.',
        keys: [
          'button.legacyReopen',
          'advice.legacyOldDataKept',
          'button.deleteLegacy',
          'advice.deleteLegacy',
          'label.confirmDeleteLegacy',
          'button.downloadLegacyJson',
          'button.legacyDeleteOld',
        ],
        parts: ['settings.data.legacy-delete'],
        only: 'only if the old app left data in this browser',
      },
    ],
  },

  {
    n: 6,
    id: 'w6-extras',
    file: 'w6-extras.html',
    title: 'Extras And Rare States',
    short: 'Extras and rare states',
    steps: [
      {
        id: 'w6.01',
        title: 'The palette',
        do: 'Tap "find it" at the end of the tab row, then type a letter. On a keyboard, press Ctrl and K together.',
        see: 'A search field, a list of views and exercises, and a line when nothing matches.',
        keys: [
          'hero.spotlight',
          'label.spotlightQuery',
          'label.spotlightResults',
          'label.spotlightView',
          'label.spotlightExercise',
          'advice.noSpotlightMatch',
        ],
        parts: ['popup.spotlight'],
      },
      {
        id: 'w6.02',
        title: 'The Konami overlay',
        do: 'On a keyboard, press up, up, down, down, left, right, left, right, B, A.',
        see: 'An overlay with one line on it and a way out.',
        keys: ['status.konami'],
        parts: ['popup.konami'],
        only: 'only on a device with a keyboard',
      },
      {
        id: 'w6.03',
        title: 'The block change',
        do: 'Finish the last session of a block and open today.',
        see: 'A cutscene counting what the block held, with a control to move on.',
        keys: [
          'status.blockTransition',
          'label.blockSessionsCompleted',
          'label.blockSetsLogged',
          'label.blockMassMoved',
          'label.blockSpecimens',
        ],
        parts: ['popup.phase-transition'],
        only: 'only when a training block ends',
      },
      {
        id: 'w6.04',
        title: 'The missed-week popup',
        do: 'Open the app on the first day after a week that missed its target. Tap the clip once to unmute it.',
        see: 'Your clip if you stored one, two lines about the week, and a single dismiss control.',
        keys: [
          'hero.motivationPreview',
          'advice.motivationPreview',
          'advice.weekMissed',
          'advice.weekMissedNone',
          'advice.tapForSound',
          'advice.tapToMute',
        ],
        parts: ['popup.missed-week'],
        only: 'only after a missed week, or from "sneak peek" in settings',
      },
      {
        id: 'w6.05',
        title: 'The update prompt',
        do: 'Leave the app open while a new build is published, then look at the top of the screen.',
        see: 'A banner offering a reload.',
        keys: ['banner.update.tag', 'banner.update.body', 'button.reload'],
        parts: ['shell.update-prompt'],
        only: 'only when a new build is waiting',
      },
      {
        id: 'w6.06',
        title: 'The save error banner',
        do: 'Read the three states below. They appear when the browser refuses to write the document.',
        see: 'A banner naming which failure it is, with an export and a retry.',
        keys: [
          'banner.saveQuota.tag',
          'banner.saveQuota.body',
          'banner.saveUnavailable.tag',
          'banner.saveUnavailable.body',
          'banner.saveFailed.tag',
          'banner.saveFailed.body',
          'button.exportData',
          'button.retrySave',
          'button.exportStoredCopy',
        ],
        parts: ['shell.save-error'],
        only: 'only when a save fails, so read the strings here rather than reaching them',
      },
      {
        id: 'w6.07',
        title: 'The load error banner',
        do: 'Read the state below. It appears when the stored document cannot be read.',
        see: 'A banner with one control that downloads whatever was on disk.',
        keys: ['banner.loadInvalid.tag', 'banner.loadInvalid.body', 'button.exportStoredData'],
        parts: ['shell.load-error'],
        only: 'only when the stored document cannot be read',
      },
      {
        id: 'w6.08',
        title: 'The old data offer',
        do: 'Open the app in a browser that still holds the old app data.',
        see: 'A panel saying what was found, the units it must be told, and two controls.',
        keys: [
          'hero.legacyImport',
          'advice.legacyFound',
          'disclosure.whatTransfers',
          'disclosure.legacyTransfers',
          'label.legacyLoadUnit',
          'advice.legacyUnitRequired',
          'label.legacyUnitKg',
          'label.legacyUnitLb',
          'disclosure.legacyBodyMassEvidence',
          'label.legacyBodyMassUnit',
          'label.legacyMassUnitKg',
          'label.legacyMassUnitLb',
          'advice.legacyNothingDeleted',
          'button.legacyPreview',
          'button.legacyDismiss',
        ],
        parts: ['popup.migration.explain'],
        only: 'only if the old app left data in this browser',
      },
      {
        id: 'w6.09',
        title: 'The old data preview',
        do: 'Tap "Preview import".',
        see: 'What the import found, what it refused, and what it could not match, before anything is written.',
        keys: [
          'hero.legacyPreview',
          'disclosure.whatWasRefused',
          'disclosure.whatWasNotMatched',
          'advice.legacyRefused',
          'advice.legacyApplyFailed',
          'button.legacyApply',
        ],
        parts: ['popup.migration.preview'],
        only: 'only if the old app left data in this browser',
      },
      {
        id: 'w6.10',
        title: 'The old data result',
        do: 'Tap "Keep import", then choose whether to keep the old keys.',
        see: 'What was written, and what happens to the old data now.',
        keys: [
          'hero.legacyDone',
          'advice.legacyStored',
          'advice.legacyStoreUnconfirmed',
          'advice.legacyOldDataDeleted',
          'button.legacyKeepOld',
          'button.legacyClose',
        ],
        parts: ['popup.migration.applied'],
        only: 'only if the old app left data in this browser',
      },
      {
        id: 'w6.11',
        title: 'The reminders panel, the other states',
        do: 'Read the state lines below. The panel shows one of them, and which one depends on the browser, the permission and whether push has synced.',
        see: 'One line in the reminders block saying what push is doing right now, and an error line when a subscribe or a sync fails.',
        keys: [
          'status.remindersUnsupported',
          'status.remindersNeedInstall',
          'status.remindersDenied',
          'status.remindersOff',
          'status.remindersNeedReenable',
          'status.remindersPending',
          'status.remindersActive',
          'advice.reminderSubscribeFailed',
          'advice.reminderSyncFailed',
        ],
        parts: ['settings.reminders'],
        only: 'only one of these shows at a time, so read the rest here rather than reaching them',
      },
    ],
  },
];

/** Every step, flattened, in walk order. */
export const ALL_STEPS = STAGES.flatMap((s) => s.steps);
